\documentclass[pdftex,12pt,a4paper]{article}

\input{title_bor_knitr}

% RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW 
% RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW RNW 

\title{Exams collection. Growing. Mathematics for economists (MFE), Methods of optimal solution (MOS) }

\providecommand{\grad}{\mathrm{grad}\,}
\usepackage{commath} % for derivatives etc

\begin{document}
%\maketitle
\parindent=0 pt % no indent

<<"setup", echo=FALSE, include=FALSE>>=
library(knitr)
library(ggplot2) 
library(gridExtra)
opts_chunk$set(cache=TRUE,
               dev="cairo_pdf",
               warning=FALSE,
               tidy=FALSE) # кэшируем все куски по умолчанию
@



\maketitle

\tableofcontents{}

\section{2008-2009}

\subsection{MFE, mock, ??.11.08}

Calculators are not allowed. \\

Candidates should attempt:\\
- all questions from Part A \\
- two of three questions from Part B. \\


Part A. \\

Problem 1. $[10]$ \\
Find and sketch on the plane the sets:\\
a)	$([1;3)\times[-1;4))\cap ((2;5]\times(2;5])$\\
b)	$([1;3)\times[-1;4))\cup ((2;5]\times(2;5])$\\
c)	$([1;3)\times[-1;4))\backslash ((2;5]\times(2;5])$\\

Problem 2. $[10]$ \\
Calculate the directional derivative of the function $f(x,y)=2x^3+2y^2$ at the point $A(1;2)$ in the following directions:\\
a)	$\vec{l}=(1;3)$ \\
b)	$\vec{l}$ which is orthogonal to the curve given by the equation $x^2+y^2=5$\\
c)	Direction of the fastest growth of $f(x,y)$\\

Problem 3. $[10]$ \\
Consider the following system of equation:\\
$\left\{\begin{array}{l}
xyzw+2x^3y^3z^3+4w^3=7\\
x+y+z^3+w^3+w^2z^2=5\\
\end{array}\right.$\\
a)	Does this system define functions $z(x,y)$ and $w(x,y)$ at a point $x=1$, $y=1$, $z=1$, $w=1$?\\
b)	If it's possible find $\frac{\partial z}{\partial x}$ and $\frac{\partial w}{\partial y}$ at that point\\

Problem 4. $[10]$ \\
Find the Hesse matrix of the function $f(x,y)=(2+cos(x))^{sin(y)+5}$\\
Comment: clearly state Young theorem if you use it \\

Problem 5. $[10]$ \\
Find the total differential for the function $f(x,y)=x^2y^2+xy^2+2x+4y$\\
Using the total differential find approximately $f(1.001,1.999)$ \\

Problem 6. $[10]$ \\
Using the chain rule find all the first derivatives of  $p(a,b)$ where $p(a,b)=f(x(a,b),y(a,b))$, $x(a,b)=a^2+ab$ and $y(a,b)=b^3+ab$ \\


Part B. \\

Problem 7. $[20]$ \\
Find the critical points of the function $f(x,y,z)=x^3-y^3+9xy-z^2e^{-z^2}$\\
Classify them using the Hesse matrix. \\

Problem 8. $[20]$ \\
The individual lives for two periods.  He has a utility function $U(c_{1},c_{2})=u(c_{1})+\beta u(c_{2})$. In each period his wage is equal to $w$. His budget constraint requires that his period 1 consumption be his wage $w$ minus any savings, $c_{1}=w-s$. The government taxes savings at the rate $q$ per dollar saved. So his second period consumption will be $c_{2}= w + (1+ r)s(1-q)$.  The individual takes $q$, $r$, $w$ as given. The individual seeks to maximise his utility $U$.\\
a)	Find the first order condition for the optimal savings amount\\
b)	Using the implicit function theorem find $\frac{\partial s}{\partial q}$\\
c)	Find $\frac{\partial s}{\partial q}$ explicitly if $u(c)=ln(c)$\\

Problem 9. $[20]$ \\
A firm sells its output into a perfectly competitive market and faces a fixed price $p$. It hires labor in a competitive labor market at a wage $w$, and rents capital in a competitive capital market at rental rate $r$. The production function is $f(L, K)$. The firm seeks to maximize its profits. Both factors are used in positive amounts in the optimal point. \\
a)	Express the profit $\pi$ as a function of $L$ and $K$\\
b)	Find necessary first order conditions for a profit-maximizing point $(L^{*},K^{*})$\\
c)	Find the second order conditions sufficient for maximum (two inequalities)\\
d)	Using the implicit function theorem find $\frac{\partial K^{*}}{\partial w}$.  Is it positive or negative if you additionally know that $\frac{\partial^{2}\pi}{\partial L\partial K}>0$?\\



\subsection{MFE, fall semester exam, 21.01.2009}

Lecturer: K.A. Bukin, Classteachers: B.B. Demeshev, I.O. Kachkovski


SECTION A. Answer all FOUR questions from this section (60 marks in total)

\begin{enumerate}
\item Find the gradient of $f(x,y) =\frac{x^2y}{\sqrt{x^2+y^2}}$
at the point $M(1,3)$. Compute the derivative of $f$ at $M$ in direction of the vector $\{-1, 1\}$.

\item Calculate all partial derivatives of the first and second order of $u$ with respect to $x$ and $y$ if $u=f (\xi, \eta)$ and $\xi=x+xy$, $\eta=x/y$.

\item Consider the system of equations
\[
\left\{
\begin{array}{l}
x_1^2+x_1 y_1+x_2 y_2  = 3 \\
x_2^2+x_1 y_2 -x_2 y_1 =1
\end{array}
\right.
\]
Are implicit functions $y = y(x)$ and $x = x(y)$ defined around the point $M(1, 1, 1, 1)$?
Here $y$ denotes the vector with components $y_1$ and $y_2$ and the same notation holds for $x$. 
If your answer is affirmative, find $\partial y_1/\partial x_1$ and $\partial x_2/\partial y_2$ at the point $M$.

\item Find all stationary points of $f(x,y) = x^4 + y^4-4xy + 1$. Classify them as local minimum, maximum or saddle point.
\end{enumerate}


SECTION B
Answer TWO of the three questions from this section (20 marks each)
\begin{enumerate}[resume]
\item Consider a problem of identifying Pareto–optimal allocations in the two goods
economy with the two agents having identical utility functions $U_1(x_1 , y_1)= x_1 y_1$ and
$U_2(x_2, y_2) = x_2 y_2$, where $x_i$ and $y_i$ denote respectively the amounts of goods $x$ and $y$ that are allocated to agent $i = 1, 2$. Given a weight $\alpha \in (0, 1)$, the solution of that problem can be found by maximizing the <<weighted>> utility function $\alpha U_1 + (1 - \alpha)U_2$ with respect to all the variables subject to the resource constraints $x_1 + x_2 = w_1$, $y_1 + y_2 = w_2$. In this economy $w_1$, $w_2$ are positive endowments.
\begin{enumerate}
\item Using the Lagrangean derive the necessary conditions for extremum and solve the
system of equations.
\item Without applying the second–order conditions explain why the solution
$(x_1^* , x_2^* , y_1^* , y_2^* )$
is the maximum of the problem stated above.
\item Calculate the value of the <<weighted>> utility function at the Pareto-optimal allocation and compare it with the case when all the endowment in $x$ and $y$ is given to a single
agent. How would you explain a difficulty you may find here?
\end{enumerate}

\item A firm’s inventory $I(t)$ is depleted at a constant rate per unit time, i.e. $I(t) = x-\delta t$, where $x$ is an amount of good reordered by the firm whenever the level of inventory is
zero. The order is fulfilled immediately. The annual requirement for the commodity is
$200$ units and the firm orders the commodity $n$ times a year where $200 = nx$. The firm
incurs two types of inventory costs: a holding cost and an ordering cost. Since the average
stock of inventory is $x/2$, the holding cost equals $C_h x/2$, the cost of placing one order is
$C_o$, and with $n$ orders a year the annual ordering cost equals $C_o n$.
\begin{enumerate}
\item Minimize the cost of inventory $C = C_h x/2 + C_o n$ by choice of $x$ and $n$ subject to
the constraint $nx = 200$ by the Lagrange multiplier method.
\item Use the envelope theorem to approximate the change in the minimal cost if the
requirement for the commodity rises to $204$ units.
\end{enumerate}


\item Use the Lagrange multiplier method to prove that the triangle with maximum area
that has a given perimeter $2p$ is equilateral. Be sure to justify that the extreme you find
is indeed maximum.


\textit{Hint 1:} Use Heron’s formula for the area:
\[
A=\sqrt{p(p - x)(p - y)(p - z)}
\]
where $x$, $y$ and $z$ are the lengths of the sides.


\textit{Hint 2:} You may find that maximizing $A^2$ instead of just $A$ will require somewhat more
pleasant calculations while giving the same answer.
\end{enumerate}

\section{2009-2010}

\subsection{MFE, fall semester exam, 19.01.2010}

Lecturer: K. A. Bukin, Classteachers: A. Arlashin, I. Kachkovski, M. Martinovic


Marks will be deducted for insufficient explanation within your answers. Total duration
of the exam is 120 min.


Variant I


SECTION A. Answer all six questions from this section (10 marks each)

\begin{enumerate}

\item Consider the function $f(x,y)=(1+x)/y^2$. On the $(x,y)$-plane, sketch several level curves of $f$. Calculate and sketch unit length vectors indicating directions of the most rapid growth of $f$ at points $(1, 1)$ and $(3, -1)$.

\item Use the first-order differential to approximate 
$\sqrt[3]{4\cdot 0.9^2+2.2^2}$

\item Find the equation of the tangent plane to the surface given by $x^3+z^3-3xz=y-1$ at the point $(1, 4, 2)$.

\item Find $\partial^2 u / \partial x \partial y$ and $\partial^3 u / \partial x \partial z^2$ if $u=f(s,t)$ and $s=x/y$, $t=y/z$. Assume that $f$ has continuous third-order partial derivatives.

\item Given the system
\[
\begin{cases}
xe^{u+v}+2uv=1 \\
ye^{u-v}-\frac{u}{1+v}=2x
\end{cases}
\]
find $du$ and $dv$ at $x_0 = 1$, $y_0 = 2$, $u_0 = 0$, $v_0 = 0$.

\item Use Lagrange multipliers to find the dimension of a rectangular box with the least
possible surface area among those with a volume of 27 m$^3$. Make sure you check the second
order condition for minimisation.
\end{enumerate}

SECTION B. Answer both questions from this section (20 marks each)

\begin{enumerate}[resume]
\item Dr. Cooper is a two-period consumer and his utility is $u(c_0 , c_1) = \ln c_0 + 0.8 \ln c_1$, with $c_0$ the initial period consumption and $c_1$ the second period consumption. He gets income of $Y_0$ and $Y_1$ in these two periods respectively, and can borrow and lend money at the same interest rate of $r$.


That means, if Dr. Cooper consumes less than $Y_0$ in the initial period, then the difference is saved and results in the second period additional income, equal to $(Y_0 - c_0)(1 + r)$, of course. If he decides to consume more than $Y_0$ in the initial period, he has to borrow and repay the borrowed amount together with interest payments in the second period, thus lowering his second-period consumption (to what amount?).
\begin{enumerate}
\item Show that irrespective of whether Dr. Cooper goes borrowing or lending, his budget
constraint is
\[
c_0 (1 + r) + c_1 = Y_0 (1 + r) + Y_1
\]
\item Sketch the budget constraint and several indifference curves on the $(c_0 , c_1)$-plane.
\item Suppose now that $r = 0.4$ and $Y_0 = Y_1 = 10$. Set up the utility optimisation problem with variables $c_0$ and $c_1$. Use Lagrange multipliers to solve it. Justify that the point you have found is the point of maximum.
\item Using the Envelope Theorem, approximate the change in Dr. Cooper’s maximum
utility if the interest rate rises to $0.45$ with unchanged income in both periods.
\end{enumerate}

\item Consider the Edgeworth exchange economy with two agents, Robinson and Friday,
and two goods, wheat and fish. Robinson has the utility of possessing $w$ units of wheat
and $f$ units of fish equal to $u_R(w, f) = wf$, Friday’s utility is $u_F(w, f) = w^2 f$. There is one unit of wheat and one unit of fish in the economy.
\begin{enumerate}
\item Set up (but do not solve) the problem of optimisation of Friday’s utility given the
fixed level of Robinson’s utility, say, $u_R(w, f ) = 1/3$. There should be 4 variables (the product levels, or allocations, for Robinson and Friday) and 3 equality constraints.
\item The problem above can also be set up in 2 variables with 1 constraint: maximize
$(1-w)^2(1-f)$ subject to $wf = 1/3$. Use Lagrange multipliers to solve it. Find the optimal product levels of both agents. Do not check the second-order condition.
\item In the context, explain the geometric significance of the equation
\[
\nabla u_R (w, f ) = \lambda\cdot \nabla u_F (1 - w, 1 - f )
\]
where $\lambda$ is some real number.
\item The optimal levels in (ii) are also the solution of the problem of optimising Robinson’s utility given some fixed level of Friday’s utility, $u_F(w,f) = a$. What is the value of $a$? What is the optimal value of Robinson’s utility under the given constraint?
\end{enumerate}


\end{enumerate}


\section{2010-2011}

\subsection{MFE, fall semester exam, 18.01.2011}

Variant 4, Classteachers: A.Arlashin, G.Sharygin, S.Provornikov

Section A.
Answer all 6 questions from this section (10 marks each)

\begin{enumerate}
\item Let $\bar{n}$ be the unit normal at a point $M_0( x_0 , y_0 , z_0 )$ to the sphere represented by the equation $x^2+y^2+z^2=16$ in $R^3$. The point $M_0$ belongs to that sphere.
\begin{enumerate}
\item Find the components of $\bar{n}$ as the functions of $M_0$.
\item Find the set of points on the sphere at which the directional derivative of the function $u( x, y, z )=x-z$ in the direction of $\bar{n}$ turns to zero.
\end{enumerate}

\item Suppose $f(x,y)$ is a twice differentiable function. Let $x$ and $y$ be defined in terms of $u$, $v$ as follows: $x(u,v)=ue^{2v}$, $y(u,v)=u^2-v^2$. Let $F(u,v)=f(x(u, v), y(u, v))$.
Calculate $F_{uu}''$ and $F_{uv}''$.
\item Find the linear approximation of the function $\cos(e^x+e^y)$ in the neighborhood of the point $(\ln (\pi/4), \ln (\pi/4))$.

\item In the economy producing two goods $x$ and $y$ , the production possibilities set (PPS) is given by the system of inequalities
$ \left\{ x^2-xy+2.5y^2\leq 450, \, x\geq 0, \, y\geq 0 \right\} $
By definition the marginal rate of transformation is defined as 
$ MRT=-\frac{dy}{dx}$
, where derivative (if it exists) is taken at a point on the boundary of PPS which is called Production Possibilities Frontier.
\begin{enumerate}
\item  By completing perfect squares prove that PPS is a bounded set.
\item Using the Implicit Function Theorem find MRT for that economy in terms of $x$, $y$. Consider $x>0$ and $y>0$.
\item Find point(s) at which $MRT=1$.
\end{enumerate}

\item A two goods producer is a monopolist and it faces the inverse demand functions $p_x=60-2x$ and $p_y=50-3y+x$ where $x$, $y$ are produced positive quantities. Let the total cost function be $C(x,y)=x^2+2y^2+xy$. Find production levels that maximize firm’s profit. Use second-order conditions to verify maximization.

\item In the macroeconomic linear IS-LM model for the closed economy
$Y=\bar{C}+m(Y-T)+G+\bar{I}-ar$ and $\bar{L}+bY-cr=M_s$, where $M_s$ is money supply, $r$ --- interest rate, $G$ --- government expenditures, $T$ --- lump sum tax and the constant parameters $\bar{C}>0$, $0<m<1$, $\bar{I}>0$, $a>0$, $\bar{L}>0$, $b>0$, $c>0$. Find the formulas for $dr/dT$, $dY/dT$. Assume that government expenditures and money supply are fixed exogenous variables.
\end{enumerate}


Section B
Answer both questions from this section (20 marks each)

\begin{enumerate}[resume]
\item In the economy described by the production possibilities set in question four from section A, the world prices on goods are set as follows: $p_x=5$, $p_y=4$. In order to maximize its national income the economy maximizes the objective function $5x+4y$ on the constraint set 
$ \left\{ x^2-xy+2.5y^2\leq 450, \, x\geq 0, \, y\geq 0 \right\} $.
Find the produced quantities in that economy. You may not use the Kuhn-Tucker formulation here. Can the Weierstrass Theorem on attainment of the greatest and the least values be applicable in that maximization problem? Explain.

\item A consumer splits her time $\bar{L}$ hours a week between labor and leisure. Her utility function is represented by $u(c,l)=c^{\alpha}l^{1-\alpha}$, where $c$ is the amount of consumption and $l$ is leisure in hours and $0<\alpha<1$. The weekly budget constraint is written as $pc+wl=w\bar{L}$,
where $p$ is the price of consumption, $w$ is the hourly wage rate.
\begin{enumerate}
\item Find the consumer’s optimal bundle $(c^*,l^*)$. Justify your answer by checking second-order conditions or otherwise.
\item Let $\alpha=3/4$, $\bar{L}=168$, $p=16$, $w=8$. Using Envelope Theorem estimate the change in the maximum value of her utility if the wage rate has decreased by $0.5$.
\end{enumerate}
\end{enumerate}


\section{2011-2012}

\subsection{MFE, mock, 31.10.11}
Marks will be deducted for insufficient explanation within your answers. Sections A and B will make up 60\% and 40\% of the exam grade, respectively. Total duration of the exam is 120 min. \\ \\
\textbf{SECTION A}

Answer SIX of the six questions from this section.

\begin{enumerate}

\item Estimate value of $\sin^2(61^{o})\cdot\tan(31^{o})$ by linear approximation using derivatives at $60^{o}$ and $30^{o}$. Convert degrees into radians first.

\begin{enumerate}
\item Degrees to radians. 2 points.
\item Appoximation. 8 points.
\end{enumerate}


\item Let $D$ be the domain of the function $f(x,y)=\ln(x)+\sqrt{y-x}$. Find $D$, the set $D^{o}$ of internal points of $D$, the set $\partial D$ of boundary points of $D$.

\begin{enumerate}
\item The set $D$. 4 points.
\item Internal points. 3 points.
\item Boundary points. 3 points.
\end{enumerate}


\item Consider the function $f(x,y)=x^2+y^3-xy+3y$ at the point $(2;1)$. Find all the directions in which the  growth rate of the function constitutes $60\%$ of the maximal possible growth rate at that point.

\begin{enumerate}
\item Gradient and its length. 3 points.
\item Equation for direction. 3 points.
\item Solution of the equation. 4 points. One missing solution implies penalty 2 point.
\end{enumerate}



\item Find the Hesse matrix of $f(x,y)=y\ln(x^2+y)$. Clearly state Young's theorem if you use it. 

\begin{enumerate}
\item First derivatives. 2 points.
\item Second derivatives without the use of Young's theorem. 8 points . 
\item Second derivatives with the use of Young's theorem. 6 points for derivatives. 2 points for the statement of the theorem. 
\end{enumerate}



\item Consider the function 
\begin{equation}
f(x,y)=
\begin{cases}
	\frac{xy}{\sqrt{x^2+y^2}}, \mbox{if} (x,y)\neq (0,0) \\
	0, \mbox{if} (x,y)=(0,0)
\end{cases}
\end{equation}
Is this function continuous at $(0;0)$? 

\begin{enumerate}
\item 10 points. Answer without proof = 0 points.
\end{enumerate}


\item The value of $y$ is determined as a function of $t$ by the equation
\begin{equation}
\int_{0}^{t}f(x,y)dx=1
\end{equation}
Find $dy/dt$

\begin{enumerate}
\item Mention of the formula $dy/dt=-\frac{G_t}{G_y}$. 2 points.
\item All the rest. 8 points
\end{enumerate}


\end{enumerate}

PLEASE TURN OVER

\textbf{SECTION B}

Answer TWO of the two questions from this section.


\begin{enumerate}
\item Find all critical points of the function $z=z(x,y)$ implicitly defined by the equation
\begin{equation}
x^2+y^2+z^2-xz-yz+x+y+4z+1=0
\end{equation}

\item Let the production function $q=F(K,L)$ be twice continuously differentiable. Marginal rate of technical substitution is defined by the formula
\begin{equation}
MRTS=\frac{\frac{\partial F}{\partial L}}{\frac{\partial F}{\partial K}}
\end{equation}
The derivatives in the denominator and numerator are taken while the same amount of the output $q$ is fixed.
Show that under the conditions $F_L>0$, $F_K>0$, $F_{LL}<0$, $F_{KK}<0$, $F_{LK}\geq 0$, the marginal rate monotonously declines with the growth of the factor $L$. In other words $\frac{\partial MRTS}{\partial L}<0$.
\end{enumerate}

\subsection{MFE, fall semester exam, 29.12.11}

Lecturer: K. Bukin \\
Classteachers: B. Demeshev, A. Kalchenko, S. Slavnov, D. Yesaulov \\

Marks will be deducted fro insufficient explanations within your solutions. Exam lasts for 120 minutes. \\

Section A. Answer all 6 questions from this section (10 marks each) \\

\begin{enumerate}

\item The function $f(x,y)$ is given by $f(x,y)=u^2(x,y)+v^3(x,y)$. The values of $u$ and $v$ and their gradients at the point $(x,y)=(1,1)$ are also known, $u(1,1)=3$, $v(1,1)=-2$, $\grad u=(1,4)$, $\grad v=(-1,1)$. Find $\grad f$ if $u,v \in C^1$.
\item Find the Hesse matrix of the function $f(x,y)=\int_{x-3y}^{2x+y}h(t)\,\dif t$ if $h\in C^1$.

\item Determine the values of $a$ for which the quadratic form $x^2 + 2axy + 2xz + z^2$ is positive definite, negative definite, positive semidefinite, negative semidefinite, and indefinite.

\item Given the system of two equations $x^2+y^2=\frac{1}{2}z^2$ and $x+y+z=2$, find $\od{x}{z}$ and $\od{y}{z}$ in the neighborhood of the point $(1,-1,2)$.

\item Find the maxima and minima of the function $f(x,y,z)=xyz$ subject to the constraints $x+y+z=5$ and $xy+yz+xz=8$, $x>0$, $y>0$, $z>0$.

\item If the function $y$ is given by $y(x)=\frac{1}{2}(e^x+e^{-x})$, check that $\od{x}{y}=\frac{1}{\sqrt{y^2-1}} $.
\end{enumerate}

Section B. Answer both questions from this section (20 marks each) \\

\begin{enumerate}
\addtocounter{enumi}{6}
\item Consider the following maximization problem $f(x,y,a,b)=ax^2-x+by^2-y$, where $a$ and $b$ are real numbers.
\begin{enumerate}
\item Derive $(x^*,y^*)$ --- the point that satisfies the first order conditions. 
\item Specify the conditions for $a$ and $b$ to ensure that the point $(x^*,y^*)$ is the maximizer.
\item Use the Hessian to specify conditions for concavity and convexity of $f$ depending on the values of parameters.
\item Solve the comparative statics problem: compute $\pd{y^*}{a}$ and $\pd{y^*}{b}$  as $a$ and $b$ marginally change.
\item Using one of the envelope theorems find the rate of change of the value function $f(x^*,y^*,a,b)$ as the result of the marginal change in $a$ and $b$.
\end{enumerate}

\item Robinson Crusoe splits his time $\bar{L}$ hours a week between labor and leisure. His utility function is represented by $u(c,l)=\alpha \ln c+(1-\alpha)\ln l$, where $c$ is the amount of food and $l$ is leisure in hours and $0<\alpha<1$. The food is produced by him in accordance with the production function $c=\sqrt{\bar{L}-l}$.
\begin{enumerate}
\item Find Robinson’s optimal bundle $(c^*,l^*)$ that provides him with the maximum utility (welfare) possible. Justify your answer by checking second-order conditions or otherwise.
\item Let $\alpha=1/4$, $\bar{L}=168$. Using the envelope theorem, estimate the change in the maximum value of his welfare if his utility function has slightly changed to become $u(c,l)=\frac{1}{5} \ln c+\frac{4}{5}\ln l$.
\end{enumerate}

\end{enumerate}

\subsection{MFE, fall semester sols}

\begin{enumerate}
\item[2]
$f_{xx}=4h'(2x+y)-h'(x-3y)$,
$f_{xy}=2h'(2x+y)+3h'(x-3y)$,
$f_{yy}=h'(2x+y)-9h'(x-3y)$,


\item[7] 
\begin{enumerate}
\item $x^*=1/2a$, $y^*=1/2b$
\item SOC for maximum: $a<0$, $b<0$
\item Convex if $a\geq 0$, $b\geq 0$, concave if $a \leq 0$, $b \leq 0$.
\item $\partial x^*/\partial b=0$, $\partial x^*/\partial a=-1/2a^2$,
\item  $\partial f^*/\partial a= x^{*2}=1/4a^2$
\end{enumerate}
\end{enumerate}

\subsection{MFE, fall semester retake, 25.01.12 }

Lecturer: K. Bukin. Classteachers: B. Demeshev, A. Kalchenko, S. Slavnov, D. Yesaulov \\

Section A. Answer all 6 questions from this section (10 marks each) 

\begin{enumerate}

\item For the function $f(x,y)=2xy+3$ find the level curves and the equations for their tangents at the points $(1,2)$ and $(2, 2)$.

\item The population of a certain country grows exponentially, $N_t= N_{1990}\cdot \exp (r(t-1990))$. The population was 70 million in 1990 and 80 million in 2000,
what will be the population in 2013?

\item Use the chain rule to find $f'(x)$ and $f''(x)$ for $f(x)=u(a,b,x)$ where $a=\cos(x)$ and $b=x^3$.

\item The system of equations defines $x(z)$ and $y(z)$:
\begin{equation}
\begin{cases}
x^2+zxy+y^2+6z+y^3=10 \\
y^3x^2+3x+2y+z=7 \nonumber
\end{cases}
\end{equation}
Find $x'(z)$ and $y'(z)$ at the point $x=1$ and $y=1$.

\item Consider the function $f(x,y)=x^2+y^3-xy+3y$ at the point $(2;1)$. Find all the directions in which the  growth rate of the function constitutes $60\%$ of the maximal possible growth rate at that point.

\item Consider the objective function $f(x,y)=4kx^3+k^2xy+3ky^4-13x-13y$. The point $(x,y)=(1,1)$ is the maximum of the function. 
\begin{enumerate}
\item Find the value of $k$
\item Find the approximate increase of the maximum value if $k$ will change by $\Delta k=0.01$
\end{enumerate}


\end{enumerate}

Section B. Answer both questions from this section (20 marks each) 

\begin{enumerate}
\addtocounter{enumi}{6}

\item We wish to build a picnic zone for the travellers along a highway. The picnic zone should be rectangular with an area of 1000 m$^2$ and should have a fence on the three sides not adjacent to the highway. The price of one meter of fence is equal to \$ 20. 
\begin{enumerate}
\item Find the dimensions of the picnic area that minimize the fencing costs.
\item Using hessian or otherwise check that you have found the costs-minimizing solution.
\item Using the Envelope theorem estimate the change in the costs if we increase the area of the picnic zone by 1 m$^2$. 
\end{enumerate}

\item A monopolistic firm with the cost function $TC(Q)=30+15Q+Q^2$ sells a single product in two separate markets. The demand functions for these markets are given by $Q_1=25-P_1$, $Q_2=29-P_2$.
\begin{enumerate}
\item Find the optimal quantities $Q_1$, $Q_2$ to be supplied to the respective markets in order to maximize the profit. Using hessian or otherwise check the second order condition.
\item Calculate the point elasticity of demand for each of the three markets. Is it true that the optimal price is negatively related to the absolute value of elasticity at the optimal levels of output?
\item Using the Envelope theorem estimate the change in the optimal profit if the demand on the second market changes to $Q_2=29.2-1.1P_2$.
\end{enumerate}


\end{enumerate}




\subsection{MFE, mock exam, 02.04.12}


Time allowed 120 minutes.

Students should answer all of the following eight questions. Calculators are not permitted in the exam. Marks will be deducted for insufficient explanations within your answers.

Section A: 10 points  each question.
\begin{enumerate}
\item Determine whether the function $f(x,y)=\ln(5x+y)-5(x+y)^2$ is convex (concave up), concave (concave down), strictly convex, strictly concave or neither.

%Solution. Find Hesse matrix, $\Delta_1=-25/(5x + y)^2 - 10<0$, $\Delta_2=160/(5x + y)^2>0$. 

%\item It is known that the functions $f_1(x)$ and $f_2(x)$ are concave up. Is it possible that the function $h(x)=\max\{f_1(x),f_2(x)\}$ is concave down?

\item Solve the differential equation $y^{(4)}-y=\cos(x)$. The $y^{(4)}$ denotes the forth derivative of $y$.
%\item The implicit function $z(x,y)$ is given by the equation $x-z=f(y-z)$ where $f$ is some unknown differentiable function. Find $\frac{\partial z}{\partial x}+\frac{\partial z}{\partial y}$.
\item Consider the monopolist producing two distinct goods. The cost function is given by $TC(q_1,q_2)=q_1+kq_2$, where the constant $k\in (0;1)$. And the demand functions are given by $q_1(p_1,p_2)=q_2(p_1,p_2)=(p_1p_2)^{-3}$.
\begin{enumerate}
\item Find the optimal production bundle for the monopolist.
\item For which values of $k$ one of the product is priced under marginal costs? %Explain why this can happen intuitively.
\end{enumerate}
\item The density of a standard normal random variable $X$ is given by $f(x)=\frac{1}{\sqrt{2\pi}}\exp(-x^2/2)$. Taking the fact that $\int_{-\infty}^{\infty}f(x)\,dx=1$ for granted calculate $E(X^2)$, $E(X^4)$. %, $E(X^6)$.

Hint: if you don't remember, $E(X^n)=\int_{-\infty}^{+\infty}x^nf(x)\,dx$
\item The point elasticity of demand for a good is given by $\varepsilon=p^2/(p^2+4p+3)$. Find the demand function $q(p)$ given the initial condition $q(1)=1$.

%\item Expand the function $f(x)=\sqrt[3]{1+5x}\cos(x^2)$ as a power series up to $x^4$. State the range for $x$ where your expansion is correct.

\item Find the values $a$ and $b$ such that the function $f$ is homogeneous:
\[f(x,y)=2x^{b-a}y^{b+2}+y^{a+1}x^{-3b}+y^{7b}x^{-2a}\]
For the values of $a$ and $b$ you have found expand the function \[h(x)=\sqrt{1+f(x,x)}\cdot (1-\cos(f(x,x))\] as a power series up to $x^4$. State the range for $x$  where your expansion is correct.

\end{enumerate}


Section B: 20 points each question.
\begin{enumerate}
\item It is known that $x_0=0$, $x_{100}=100k$ where $k\in \mathbb{Z}$ is constant and for any $n\in\{2,3,\ldots 100\}$ the following difference equation is satisfied:
\[ x_n-2x_{n-1}+x_{n-2}=-1 \]
\begin{enumerate}
\item Find the particular solution
\item Find the maximum value of $x_n$ for $n\in\{0,\ldots,100\}$ as a function of $k$.
\end{enumerate}

\item Using the Lagrange multiplier method without reducing the number of variables by substitution find the minimum of the function \[f(x,y,z)=2x^2+4y^2+xy+8z^2+2yz\] subject to $x+y+1.5z\geq 1.2$ and $x+y+z=1$.



\begin{comment}


\item The functions $y(t)$ and $x(t)$ satisfy the following system of equations
\[
\left\{
\begin{array}{l}
x'(t)=x(t)+3y(t) \\
y'(t)=3x(t)+y(t)
\end{array}
\right.
\]
with initial conditions $x(0)=a$ and $y(0)=b$. 
\begin{enumerate}
\item Find the particular solution
\item State the conditions on $a$ and $b$ that must be satisfied if it is known that $x(t)$ decreases to a finite limit and $y(t)$ increases to a finite limit. Find these limits.
\end{enumerate}


\item Simplified Solow model. The amount of labor in the economy, $L(t)$, evolves according to the equation $L'(t)=\lambda L(t)$, where $\lambda>0$ is a constant. The amount of capital in the economy, $K(t)$, evolves according to the equation $K'(t)=sY(t)$, where the proportion of output which is invested into the capital, $s$, is a constant and the output $Y(t)$ is given by the Cobb-Duglas function $Y(t)=K^{1-a}(t)L^a (t)$.
\begin{enumerate}
\item Find the function $L(t)$ in terms of $L(0)$ and the parameters of the model.
\item Find the function $K(t)$ in terms of $L(0)$, $K(0)$ and the parameters of the model.
\item Find the limit $\lim_{t\to\infty} K(t)/L(t)$
\end{enumerate}


%Consider the following dynamic supply-demand model. The producer sets the pr



\item Consider the region $R$ described by the inequalities
\begin{equation}
\left\{
\begin{array}{l}
x^2+y^2\leq 4 \\ 
y\geq x \\ 
x,y \geq 0
\end{array} 
\right.
\end{equation}
For each point $(a,b)$ in the first quadrant use the Lagrange method to find the closest point to $(a,b)$ in the region $R$.

\item Let $Y_t$, $C_t$, $I_t$ denote national income, consumption, and investment in period $t$ respectively. The economy is described by the system
\begin{equation}
\left\{
\begin{array}{l}
Y_t=C_t+I_t\\
C_t=c+mY_t\\
Y_{t+1}=Y_{t}+rI_t
\end{array} 
\right.
\end{equation},
where $c$, $m$ and $r$ are positive constants.
\begin{enumerate}
\item Find the function $Y_t$
\item Find the asymptote of $\ln(Y(t))$ as $t$ tends to infinity.
\end{enumerate}

\item The function $f(x)$ is continuous and differentiable. Solve the following continuous analog of the simple regression problem:
\begin{equation}
\min_{a,b} \int_0^1 (f(x)-(a+bx)^2)\,dx
\end{equation}
\end{comment}


\end{enumerate}

\begin{comment}

\newpage
Mock exam on Mathematics for Economists, April 2nd, 2012.

Time allowed 120 minutes.

Students should answer all of the following eight questions. Calculators are not permitted in the exam. Marks will be deducted for insufficient explanations within your answers.

Section A: 10 points  each question.
\begin{enumerate}
\item Determine whether the function $f(x,y)=\ln(6x+y)-6(x+y)^2$ is convex (concave up), concave (concave down), strictly convex, strictly concave or neither.

%Solution. Find Hesse matrix, $\Delta_1=-25/(5x + y)^2 - 10<0$, $\Delta_2=160/(5x + y)^2>0$. 

%\item It is known that the functions $f_1(x)$ and $f_2(x)$ are concave up. Is it possible that the function $h(x)=\max\{f_1(x),f_2(x)\}$ is concave down?

\item Solve the differential equation $y^{(4)}-y=\sin(x)$. The $y^{(4)}$ denotes the forth derivative of $y$.
%\item The implicit function $z(x,y)$ is given by the equation $x-z=f(y-z)$ where $f$ is some unknown differentiable function. Find $\frac{\partial z}{\partial x}+\frac{\partial z}{\partial y}$.
\item Consider the monopolist producing two distinct goods. The cost function is given by $TC(q_1,q_2)=q_1+kq_2$, where the constant $k\in (0;1)$. And the demand functions are given by $q_1(p_1,p_2)=q_2(p_1,p_2)=(p_1p_2)^{-3}$.
\begin{enumerate}
\item Find the optimal production bundle for the monopolist.
\item For which values of $k$ one of the product is priced under marginal costs? %Explain why this can happen intuitively.
\end{enumerate}
\item The density of a standard normal random variable $X$ is given by $f(x)=\frac{1}{\sqrt{2\pi}}\exp(-x^2/2)$. Taking the fact that $\int_{-\infty}^{\infty}f(x)\,dx=1$ for granted calculate $E(X^2)$, $E(X^4)$. %, $E(X^6)$.

Hint: if you don't remember, $E(X^n)=\int_{-\infty}^{+\infty}x^nf(x)\,dx$
\item The point elasticity of demand for a good is given by $\varepsilon=p^2/(p^2+3p+2)$. Find the demand function $q(p)$ given the initial condition $q(1)=1$.

%\item Expand the function $f(x)=\sqrt[3]{1+5x}\cos(x^2)$ as a power series up to $x^4$. State the range for $x$ where your expansion is correct.

\item Find the values $a$ and $b$ such that the function $f$ is homogeneous:
\[f(x,y)=2x^{1+b-a}y^{b+3}+y^{a-2}x^{-3b}+y^{7b}x^{7-2a}\]
For the values of $a$ and $b$ you have found expand the function \[h(x)=\sqrt{1+f(x,x)}\cdot (\cos(f(x,x)-1)\] as a power series up to $x^4$. State the range for $x$  where your expansion is correct.

\end{enumerate}


Section B: 20 points each question.
\begin{enumerate}
\item It is known that $x_0=0$, $x_{100}=100k$ where $k\in \mathbb{Z}$ is constant and for any $n\in\{2,3,\ldots 100\}$ the following difference equation is satisfied:
\[ x_n-2x_{n-1}+x_{n-2}=-1 \]
\begin{enumerate}
\item Find the particular solution
\item Find the maximum value of $x_n$ for $n\in\{0,\ldots,100\}$ as a function of $k$.
\end{enumerate}

\item Using the Lagrange multiplier method without reducing the number of variables by substitution find the minimum of the function \[f(x,y,z)=2x^2+4y^2+xy+8z^2+2yz\] subject to $x+y+1.5z\geq 1.2$ and $x+y+z=1$.

\end{enumerate}


\newpage
Mock exam on Mathematics for Economists, April 2nd, 2012.

Time allowed 120 minutes.

Students should answer all of the following eight questions. Calculators are not permitted in the exam. Marks will be deducted for insufficient explanations within your answers.

Section A: 10 points  each question.
\begin{enumerate}
\item Determine whether the function $f(x,y)=7(x+y)^2-\ln(7x+y)$ is convex (concave up), concave (concave down), strictly convex, strictly concave or neither.

%Solution. Find Hesse matrix, $\Delta_1=-25/(5x + y)^2 - 10<0$, $\Delta_2=160/(5x + y)^2>0$. 

%\item It is known that the functions $f_1(x)$ and $f_2(x)$ are concave up. Is it possible that the function $h(x)=\max\{f_1(x),f_2(x)\}$ is concave down?

\item Solve the differential equation $y^{(4)}-y=-\sin(x)$. The $y^{(4)}$ denotes the forth derivative of $y$.
%\item The implicit function $z(x,y)$ is given by the equation $x-z=f(y-z)$ where $f$ is some unknown differentiable function. Find $\frac{\partial z}{\partial x}+\frac{\partial z}{\partial y}$.
\item Consider the monopolist producing two distinct goods. The cost function is given by $TC(q_1,q_2)=q_1+kq_2$, where the constant $k\in (0;1)$. And the demand functions are given by $q_1(p_1,p_2)=q_2(p_1,p_2)=(p_1p_2)^{-3}$.
\begin{enumerate}
\item Find the optimal production bundle for the monopolist.
\item For which values of $k$ one of the product is priced under marginal costs? %Explain why this can happen intuitively.
\end{enumerate}
\item The density of a standard normal random variable $X$ is given by $f(x)=\frac{1}{\sqrt{2\pi}}\exp(-x^2/2)$. Taking the fact that $\int_{-\infty}^{\infty}f(x)\,dx=1$ for granted calculate $E(X^2)$, $E(X^4)$. %, $E(X^6)$.

Hint: if you don't remember, $E(X^n)=\int_{-\infty}^{+\infty}x^nf(x)\,dx$
\item The point elasticity of demand for a good is given by $\varepsilon=p^2/(p^2+5p+4)$. Find the demand function $q(p)$ given the initial condition $q(1)=1$.

%\item Expand the function $f(x)=\sqrt[3]{1+5x}\cos(x^2)$ as a power series up to $x^4$. State the range for $x$ where your expansion is correct.

\item Find the values $a$ and $b$ such that the function $f$ is homogeneous:
\[f(x,y)=5x^{2+b}y^{b-a}+y^{a}x^{1-3b}+y^{7b-a-1}x^{1-a}\]
For the values of $a$ and $b$ you have found expand the function \[h(x)=\sqrt{1+f(x,x)}\cdot (\cos(f(x,x)-1)\] as a power series up to $x^4$. State the range for $x$  where your expansion is correct.

\end{enumerate}


Section B: 20 points each question.
\begin{enumerate}
\item It is known that $x_0=0$, $x_{100}=100k$ where $k\in \mathbb{Z}$ is constant and for any $n\in\{2,3,\ldots 100\}$ the following difference equation is satisfied:
\[ x_n-2x_{n-1}+x_{n-2}=-1 \]
\begin{enumerate}
\item Find the particular solution
\item Find the maximum value of $x_n$ for $n\in\{0,\ldots,100\}$ as a function of $k$.
\end{enumerate}

\item Using the Lagrange multiplier method without reducing the number of variables by substitution find the minimum of the function \[f(x,y,z)=2x^2+4y^2+xy+8z^2+2yz\] subject to $x+y+1.5z\geq 1.2$ and $x+y+z=1$.

\end{enumerate}



\newpage
Mock exam on Mathematics for Economists, April 2nd, 2012.

Time allowed 120 minutes.

Students should answer all of the following eight questions. Calculators are not permitted in the exam. Marks will be deducted for insufficient explanations within your answers.

Section A: 10 points  each question.
\begin{enumerate}
\item Determine whether the function $f(x,y)=8(x+y)^2-\ln(8x+y)$ is convex (concave up), concave (concave down), strictly convex, strictly concave or neither.

%Solution. Find Hesse matrix, $\Delta_1=-25/(5x + y)^2 - 10<0$, $\Delta_2=160/(5x + y)^2>0$. 

%\item It is known that the functions $f_1(x)$ and $f_2(x)$ are concave up. Is it possible that the function $h(x)=\max\{f_1(x),f_2(x)\}$ is concave down?

\item Solve the differential equation $y^{(4)}-y=-\cos(x)$. The $y^{(4)}$ denotes the forth derivative of $y$.
%\item The implicit function $z(x,y)$ is given by the equation $x-z=f(y-z)$ where $f$ is some unknown differentiable function. Find $\frac{\partial z}{\partial x}+\frac{\partial z}{\partial y}$.
\item Consider the monopolist producing two distinct goods. The cost function is given by $TC(q_1,q_2)=q_1+kq_2$, where the constant $k\in (0;1)$. And the demand functions are given by $q_1(p_1,p_2)=q_2(p_1,p_2)=(p_1p_2)^{-3}$.
\begin{enumerate}
\item Find the optimal production bundle for the monopolist.
\item For which values of $k$ one of the product is priced under marginal costs? %Explain why this can happen intuitively.
\end{enumerate}
\item The density of a standard normal random variable $X$ is given by $f(x)=\frac{1}{\sqrt{2\pi}}\exp(-x^2/2)$. Taking the fact that $\int_{-\infty}^{\infty}f(x)\,dx=1$ for granted calculate $E(X^2)$, $E(X^4)$. %, $E(X^6)$.

Hint: if you don't remember, $E(X^n)=\int_{-\infty}^{+\infty}x^nf(x)\,dx$
\item The point elasticity of demand for a good is given by $\varepsilon=p^2/(p^2+6p+5)$. Find the demand function $q(p)$ given the initial condition $q(1)=1$.

%\item Expand the function $f(x)=\sqrt[3]{1+5x}\cos(x^2)$ as a power series up to $x^4$. State the range for $x$ where your expansion is correct.

\item Find the values $a$ and $b$ such that the function $f$ is homogeneous:
\[f(x,y)=x^{b-2a}y^{b+2+a}+3y^{a+3}x^{-3b-2}-y^{7b-a}x^{-a}\]
For the values of $a$ and $b$ you have found expand the function \[h(x)=\sqrt{1+f(x,x)}\cdot (1-\cos(f(x,x))\] as a power series up to $x^4$. State the range for $x$  where your expansion is correct.

\end{enumerate}


Section B: 20 points each question.
\begin{enumerate}
\item It is known that $x_0=0$, $x_{100}=100k$ where $k\in \mathbb{Z}$ is constant and for any $n\in\{2,3,\ldots 100\}$ the following difference equation is satisfied:
\[ x_n-2x_{n-1}+x_{n-2}=-1 \]
\begin{enumerate}
\item Find the particular solution
\item Find the maximum value of $x_n$ for $n\in\{0,\ldots,100\}$ as a function of $k$.
\end{enumerate}

\item Using the Lagrange multiplier method without reducing the number of variables by substitution find the minimum of the function \[f(x,y,z)=2x^2+4y^2+xy+8z^2+2yz\] subject to $x+y+1.5z\geq 1.2$ and $x+y+z=1$.

\end{enumerate}

\end{comment}



\subsection{MOR, 22.05.12 }

\textbf{Section A}. Solve \textbf{two} of the following \textbf{two} problems

\vspace{12pt}

\begin{enumerate}
\item Use Lagrange multipliers method to solve optimization problem 
\[xy\to \max\]  
subject to $x\geq 0$, $0\leq y\leq 3$, $x+2y\leq 8$, $y\geq \frac{x^2}{16}+1$.
\item Solve the linear program depending on the parameter $\beta$, 
\[2x_1+4x_2+5x_3-x_4\to\min\]
subject to $x_1+x_3-x_4\geq 0$, $-x_1+x_2+\frac{1}{2}x_3+\beta x_4\geq 1$, $x_i\geq 0$.\\
For what values of $\beta$ the minimum of the objective function equals 3?

\end{enumerate}

\vspace{12pt}

\textbf{Section B}. Solve \textbf{two} of the following \textbf{three} problems

\vspace{12pt}

\begin{enumerate}[resume]
\item Find the general solution of the differential equation $y''+2y'+y=xe^{-x}+\cos(x)$
\item Solve the initial-value problem for the system of difference equations


$ \left\{ \begin{array}{l}
x_{t+1}=x_t+y_t \\
y_{t+1}=3x_t-y_t-5
\end{array} \right.$, where $x_0=y_0=0$.

\item In the model of interacting inflation and unemployment based on the Phillips relation,  both unemployment rate $U$ and expected inflation $\pi$ are the solutions of the system $\dot{\pi}=\frac{3}{4}(p-\pi)$, $\dot{U}=-\frac{1}{2}(m-p)$, where $m$ is exogenously defined positive rate of nominal money growth and $p$ is the posteriori observed inflation satisfying equation $p=\frac{1}{6}-3U+\pi$. Find the steady-state solutions for the inflation both expected and observed as well as the unemployment rate in terms of $m$. Explore the dynamic stability of solutions. What is the natural rate of unemployment?

\end{enumerate}

\vspace{12pt}

\textbf{Section C}. Solve \textbf{two} of the following \textbf{three} problems

\vspace{12pt}

\begin{enumerate}[resume]
\item Find all pure and mixed Nash equilibria in the following bimatrix game:


\begin{tabular}{c|ccc}
 & D & E & F \\ 
\hline 
A & 3;4 & 1;3 & 1;0  \\ 
B & 2;7 & 3;6 & 0;3  \\ 
C & 0;2 & 2;1 & 5;6  \\ 
\end{tabular} 
\item Two players play a version of Rock-Paper-Scissor game. Paper beats Rock, Rock beats Scissors, Scissors beats Paper. The two players simultaneously make their choice. The first player can choose any object. The second player can choose Rock or Paper. The winner receives 1 rouble from the loser. In case of a draw the wealth of a player does not change.
\begin{enumerate}
\item Construct the payoff matrix of the game.
\item Find all pure and mixed Nash equilibria
\end{enumerate}
\item Two players are trying to bribe the judge. The possible amount of bribe is any real number between 0 and 1 million roubles. The player who gives the biggest bribe is announced as the winner of the affair by the judge. The winner receives 1 million roubles. The loser gets nothing. Obviously bribes are not returned by the judge. In the case of equal bribes each player gets nothing.
\begin{enumerate}
\item Are there any pure Nash equilibria in this game?
\item Find at least one mixed Nash equilibrium.
\end{enumerate}

Short tips:
\begin{enumerate}
\item No
\item If the second player choses his move according continuous distribution function $F$ then the expected payoff of the first player for the bribe $b$ is equal to
\[
1\cdot P(b_2 \leq b) - b = 1\cdot F(b)-b
\]

If a rational player uses mixed strategies he is indifferend between the corresponding pure strategies. That means that $F(b)-b=const$ for pure strategies that are mixed. For pure strategies that are mixed the density function $f(b)=F'(b)=1$. Do I know such a random variable? Yes, I know! A uniform on $[0;1]$.

\end{enumerate}

\end{enumerate}


\subsection{MFE, retake exam, 19.09.2012}

Time allowed 120 minutes.

Students should answer all of the following eight questions. Calculators are not permitted in the exam. Marks will be deducted for insufficient explanations within your answers.

Section A: 10 points  each question.
\begin{enumerate}
%\item Determine whether the function $f(x,y)=\ln(5x+y)-5(x+y)^2$ is convex (concave up), concave (concave down), strictly convex, strictly concave or neither.

%Solution. Find Hesse matrix, $\Delta_1=-25/(5x + y)^2 - 10<0$, $\Delta_2=160/(5x + y)^2>0$. 

\item It is known that the functions $f_1(x)$ and $f_2(x)$ are concave up. Is it possible that the function $h(x)=\max\{f_1(x),f_2(x)\}$ is concave down?

%\item Solve the differential equation $y^{(4)}-y=\cos(x)$. The $y^{(4)}$ denotes the forth derivative of $y$.
\item The implicit function $z(x,y)$ is given by the equation $x-z=f(y-z)$ where $f$ is some unknown differentiable function. Find $\frac{\partial z}{\partial x}+\frac{\partial z}{\partial y}$.
\item Consider the monopolist producing two distinct goods. The cost function is given by $TC(q_1,q_2)=q_1+kq_2$, where the constant $k\in (0;1)$. And the demand functions are given by $q_1(p_1,p_2)=q_2(p_1,p_2)=(p_1p_2)^{-3}$.
\begin{enumerate}
\item Find the optimal production bundle for the monopolist.
\item For which values of $k$ one of the product is priced under marginal costs? %Explain why this can happen intuitively.
\end{enumerate}
\item The density of an exponential random variable $X$ is given by $f(x)=\exp(-x)$ for $x>0$. Calculate $E(X)$, $E(X^2)$.

Hint: if you don't remember, $E(X^n)=\int_{-\infty}^{+\infty}x^nf(x)\,dx$
\item The point elasticity of demand for a good is given by $\varepsilon=p^2/(p^2+4p+3)$. Find the demand function $q(p)$ given the initial condition $q(1)=1$.

%\item Expand the function $f(x)=\sqrt[3]{1+5x}\cos(x^2)$ as a power series up to $x^4$. State the range for $x$ where your expansion is correct.

\item Find the values $a$ and $b$ such that the function $f$ is homogeneous:
\[f(x,y)=2x^{b-a}y^{b+2}+y^{a+1}x^{-3b}+y^{7b}x^{-2a}\]
For the values of $a$ and $b$ you have found expand the function \[h(x)=\sqrt{1+f(x,x)}\cdot (1-\cos(f(x,x))\] as a power series up to $x^4$. State the range for $x$  where your expansion is correct.

\end{enumerate}


Section B: 20 points each question.
\begin{enumerate}

\item Use Lagrange multipliers method to solve optimization problem 
\[x+\ln y\to \max\]  
subject to 
$x\geq 0$, $x+y\leq 4$, $x+2y\leq 6$.

\item Let $Y_t$, $C_t$, $I_t$ denote national income, consumption, and investment in period $t$ respectively. The economy is described by the system
\begin{equation}
\left\{
\begin{array}{l}
Y_t=C_t+I_t\\
C_t=c+mY_t\\
Y_{t+1}=Y_{t}+rI_t
\end{array} 
\right.
\end{equation},
where $c$, $m$ and $r$ are positive constants.
\begin{enumerate}
\item Find the function $Y_t$
\item Find the asymptote of $\ln(Y(t))$ as $t$ tends to infinity.
\end{enumerate}


\end{enumerate}



\begin{comment}

\item It is known that $x_0=0$, $x_{100}=100k$ where $k\in \mathbb{Z}$ is constant and for any $n\in\{2,3,\ldots 100\}$ the following difference equation is satisfied:
\[ x_n-2x_{n-1}+x_{n-2}=-1 \]
\begin{enumerate}
\item Find the particular solution
\item Find the maximum value of $x_n$ for $n\in\{0,\ldots,100\}$ as a function of $k$.
\end{enumerate}

\item Using the Lagrange multiplier method without reducing the number of variables by substitution find the minimum of the function \[f(x,y,z)=2x^2+4y^2+xy+8z^2+2yz\] subject to $x+y+1.5z\geq 1.2$ and $x+y+z=1$.


\item The functions $y(t)$ and $x(t)$ satisfy the following system of equations
\[
\left\{
\begin{array}{l}
x'(t)=x(t)+3y(t) \\
y'(t)=3x(t)+y(t)
\end{array}
\right.
\]
with initial conditions $x(0)=a$ and $y(0)=b$. 
\begin{enumerate}
\item Find the particular solution
\item State the conditions on $a$ and $b$ that must be satisfied if it is known that $x(t)$ decreases to a finite limit and $y(t)$ increases to a finite limit. Find these limits.
\end{enumerate}


\item Simplified Solow model. The amount of labor in the economy, $L(t)$, evolves according to the equation $L'(t)=\lambda L(t)$, where $\lambda>0$ is a constant. The amount of capital in the economy, $K(t)$, evolves according to the equation $K'(t)=sY(t)$, where the proportion of output which is invested into the capital, $s$, is a constant and the output $Y(t)$ is given by the Cobb-Duglas function $Y(t)=K^{1-a}(t)L^a (t)$.
\begin{enumerate}
\item Find the function $L(t)$ in terms of $L(0)$ and the parameters of the model.
\item Find the function $K(t)$ in terms of $L(0)$, $K(0)$ and the parameters of the model.
\item Find the limit $\lim_{t\to\infty} K(t)/L(t)$
\end{enumerate}


%Consider the following dynamic supply-demand model. The producer sets the pr



\item Use Lagrange multipliers method to solve optimization problem 
\[x+\ln y\to \max\]  
subject to 
$x\geq 0$, $x+y\leq 4$, $x+2y\leq 6$.


\item Let $Y_t$, $C_t$, $I_t$ denote national income, consumption, and investment in period $t$ respectively. The economy is described by the system
\begin{equation}
\left\{
\begin{array}{l}
Y_t=C_t+I_t\\
C_t=c+mY_t\\
Y_{t+1}=Y_{t}+rI_t
\end{array} 
\right.
\end{equation},
where $c$, $m$ and $r$ are positive constants.
\begin{enumerate}
\item Find the function $Y_t$
\item Find the asymptote of $\ln(Y(t))$ as $t$ tends to infinity.
\end{enumerate}

\item The function $f(x)$ is continuous and differentiable. Solve the following continuous analog of the simple regression problem:
\begin{equation}
\min_{a,b} \int_0^1 (f(x)-(a+bx)^2)\,dx
\end{equation}
\end{comment}


\subsection{MOR, retake exam, 11.09.12}


\textbf{Section A}. Solve \textbf{two} of the following \textbf{two} problems

\vspace{12pt}

\begin{enumerate}
\item Use Lagrange multipliers method to solve optimization problem 
\[x+\ln y\to \max\]  
subject to 
$x\geq 0$, $x+y\leq 4$, $x+2y\leq 6$.
\item Solve the linear program depending on the parameter $\beta$, 
\[2x_1+4x_2+5x_3+x_4\to\min\]
subject to $x_1+x_3+x_4\geq 0$, $-x_1+x_2+\frac{1}{2}x_3-\beta x_4\geq 1$, $x_i\geq 0$.\\
For what values of $\beta$ the minimum of the objective function equals 3?

\end{enumerate}

\vspace{12pt}

\textbf{Section B}. Solve \textbf{two} of the following \textbf{three} problems

\vspace{12pt}

\begin{enumerate}[resume]
\item Find the general solution of the differential equation $y''+4y'+4y=xe^{-3x}+\cos(x)$
\item Consider the system of difference equations
$$ 
\left\{ \begin{array}{l}
x_{t+1}=2x_t-4y_t \\
y_{t+1}=x_t-3y_t+3
\end{array} \right.
$$
\begin{enumerate}
\item Solve the system
\item Find the equilibrium solution and check whether it's stable
\end{enumerate}

\item A policymaker desires to double in 10 periods of time the value of GDP $y_t$  produced in period $t$. Evolution of GDP over time is given by equation $4y_{t+2}-4y_{t+1}+y_t=2^t+t^2$. Is doubling of GDP feasible? If the answer is positive, is it possible to find the period $t$ when the value of $y_t$  will first exceed $2y_0$, where $y_0$ is the initial GDP?



\end{enumerate}

\vspace{12pt}

\textbf{Section C}. Solve \textbf{two} of the following \textbf{three} problems

\vspace{12pt}

\begin{enumerate}[resume]
\item Find all pure and mixed Nash equilibria in the following bimatrix game:


\begin{tabular}{c|ccc}
 & D & E & F \\ 
\hline 
A & 5;5 & 2;4 & 2;1  \\ 
B & 3;8 & 4;7 & 1;4  \\ 
C & 1;3 & 3;2 & 6;7  \\ 
\end{tabular} 
\item A man has two sons. When he dies, the value of his estate after tax is \$1000. In his will it states that the sons must specify the sum of money $s_i$ that they are willing to accept. If $s_1+2s_2\leq 1000$, then each gets the sum he asked for and the rest goes the cats’ shelter. If $s_1+2s_2> 1000$, then neither of them gets any money and the entire sum goes to the cats’ shelter. Assume that the sons only care about the money they will inherit and they ask for the whole dollars. Find the pure strategies Nash equlibria of this game.

\item Two players are trying to bribe the judge. The possible amount of bribe is any real number between 0 and 1 million roubles. The probability that the player will win is proportional to the amount of the bribe. In the case of zero bribes the probability is equal $1/2$ for each player. The winner receives 1 million roubles. The loser gets nothing. Obviously bribes are not returned by the judge. 
\begin{enumerate}
\item Are there any pure Nash equilibria in this game?
\item Find at least one mixed Nash equilibrium.
\end{enumerate}

\end{enumerate}




\section{2012-2013}

\subsection{MFE, mock, 25.10.12}

%Mathematics for economists. Mock Exam Paper. October 25, 2012 \\ 

%Lecturer: K.A. Bukin
%Class teachers: A. Arlashin, G. Sharygin, S. Provornikov

Marks will be deducted for insufficient explanation within your answers. All problems are mandatory. Sections A and B will make up 60\% and 40\% of the exam grade, respectively. Total duration of the exam is 120 min. \\

\textbf{SECTION A}
\vspace{20pt}

\begin{enumerate}
\item Consider the function $f(x,y)=x^3+y^2+xy-y^5$. Using the total differential find the approximate value of $f(1.01,0.98)$.
\item Consider the function $f(x,y)=x^3+y^2+xy-y^5$ at the point $A=(1,1)$. I have two choices:
\begin{enumerate}
\item move from $A$ in the direction $\vec{l}=(2,1)$ by a small number $\varepsilon$ 
\item move from $A$ in the direction $\vec{m}=(1,2)$ by $2\varepsilon$
\end{enumerate}
Using the directional derivative find which choice will give me a bigger value of the function $f$ at the destination point.

\item Consider the following system of equations:\\
$\left\{\begin{array}{l}
xyz+2x^3y^3z^3+4x^3=7\\
x+y^3+z^3+xy^3+2x^2z^2=6\\
\end{array}\right.$
\begin{enumerate}
\item Does this system define functions $z(x)$ and $y(x)$ at a point $x=1$, $y=1$, $z=1$?
\item If it's possible find $y'(x)$ and $z'(x)$ at that point
\end{enumerate}

\item Determine whether the following limit exists
\begin{equation} \nonumber
\lim_{x, y\to 0} \frac{x^3+y^3}{x^2+y^2}
\end{equation}

\item Consider the function $g(u)=f(x,y)$, $x=2u$ and $y=u-u^2$. Find $g'(u)$ and $g''(u)$. Assume that $f$ has continuous second partial derivatives at any point.

\item Find the equation of a tangent plane to the surface $z=x+y^2$ at the point $(0,1,1)$.

 

\end{enumerate}

\vspace{20pt}
\textbf{SECTION B}
\vspace{20pt}

\begin{enumerate}[resume]
\item Find all the stationary points of the implicit function $z(x,y)$ given  by the equation $x^2+y^2+z^2+xy+xz+2=4x+3y$. 

\item Consider a market with the demand curve $q^d=f(p)$ and the supply curve $q^s=g(p,a)$ where the parameter $a$ describes the available technology. The goal is to find how will the equilibrium price $p^*$ and quantity $q^*$ react to the change of the technology parameter $a$. We assume that  $f'(p)<0$, $\partial g/\partial p>0$ and $\partial g/\partial a>0$.
\begin{enumerate}
\item Find $dp^*/da$, $dq^*/da$
\item If possible determine the sign of the derivatives $dp^*/da$ and $dq^*/da$. 
\end{enumerate}

\end{enumerate}


\subsection{MFE, fall semester exam, 27.12.2012} 

Sections A and B will make up 60\% and 40\% of the exam grade, respectively. Total duration of the exam is 120 min. 

\textbf{SECTION A:}
\begin{enumerate}

\item The level curves of a function $f(x,y)$ are shown below. Draw the level curves of the functions $g(x,y)=f(x+1,y)$ and $h(x,y)=f(-x,|y|)$.



<<fig.height=2,fig.width=2, echo=FALSE>>=
my_f <- function(x,y) (x-1)^2+y

x <- seq(-3,3,length.out=100)
y <- seq(-3,3,length.out=100)
h <- data.frame(x=rep(x,times=100),y=rep(y,each=100))

h$z <- my_f(h$x,h$y)

ggplot(h, aes(x=x, y=y, z=z)) + stat_contour() + theme_bw() + 
  scale_y_continuous(name="")+scale_x_continuous(name="")
#  opts(axis.text.x = theme_blank(),axis.text.y = theme_blank())

@


\item Find the local maxima and minima of the function $f(x,y)=x^4+2y^4-xy$. Determine whether the extrema you have found are global or local.

\item Find the gradient of the function $h(x,y)=f(x,y)\cdot g(x,y)$ at the point $A=(1,7)$. It is known that at the point $A$: $\grad f=(1,1)$, $\grad g=(3,3)$, $f(A)=4$, $g(A)=5$.

\item Consider the following system of equations as defining functions $y_1(x_1,x_2)$ and $y_2(x_1,x_2)$
\[
\left\{
\begin{array}{c}
x_1^3+x_1 y_1^3+x_2 y_1 y_2+y_2^3=4 \\ 
x_2+x_2^3+y_1 y_2^2+y_2^3=4
\end{array} 
\right.
\]
\begin{enumerate}
\item If possible find $dy_1$ at the point $(x_1,x_2,y_1,y_2)=(1,1,1,1)$.
\item Find approximately $y_1$ for $x_1=1.01$ and $x_2=0.98$.
\end{enumerate}
\item Find the constrained extrema of the function $f(x,y)=x+2y$ subject to $2x^2+y^2=10$.
%Short run total costs are given by $TC(q,K)=q^2+3qK+4K^2-2K$ where $q$ is the volume of output and $K$ is the amount of capital which is fixed in the short run. In the long run the firm can adapt the amount of $K$ to minimize the costs. Find the long run marginal costs using envelope theorem.

\item Find the Hesse matrix of the function $h(x,y)=\P( Z \in [2x;3y])$ where $Z$ is a standard normal random variable with probability density function given by $f(z)=\frac{1}{\sqrt{2\pi}}\exp(-z^2/2)$. It is supposed that $3y>2x$.

\end{enumerate}

\textbf{SECTION B:}
\begin{enumerate}
\item A firm’s production function is $Q=K+L+2\sqrt{KL}$, where $K>0$ and $L>0$ are capital and labor, respectively. The firm is perfectly competitive and seeks to maximize its output, but the firm is run by accountants who have imposed a fixed budget on the production of $C$ dollars per hour, which means satisfying constraint $wL+rK=C$, where $w$ and $r$ are hourly wage rate and rental rate of capital, respectively.
\begin{enumerate}
\item State the constrained optimization problem associated with that production and solve it by the Lagrange multiplier method (it is sufficient to find the optimal values of capital and labor alone).
\item Check the concavity of the production function and use it to classify the critical point.
\item Explain the economic meaning of the Lagrange multiplier in this problem. Use the appropriate envelope theorem.
\item Let $w=r$. Would it be right to conclude that if the wage rate goes up by 1\% and the rental rate goes down by the same 1\% under the fixed budget the output will not change?  How can you prove this mathematically?  
\end{enumerate}

\item It is well known that a perfectly competitive firm operating in the long-run produces at the minimum point of its average costs curve, where $p=AC=MC$. Let the $AC$ curve be U-shaped. If we assume that this particular firm uses only labor, equation $AC(y,w)=MC(y,w)$ may be used to find $y=y(w)$  as an implicit function of wages ($y$ denotes the output). Moreover, the second-order condition that guarantees the profit maximization is supposed to hold.
\begin{enumerate}
\item Show that Implicit Function Theorem can be applied, the function $y=y(w)$ exists and find its derivative.
\item If we know that at long-run equilibrium $\frac{\partial MC}{\partial w}>\frac{\partial AC}{\partial w}$  what can we say about new long-run equilibrium when the market adjusts to a small rise in wage $w$? Will the equilibrium price go up? What about the output of the firm? 
\end{enumerate}
\end{enumerate}

\subsection{MFE, fall retake 23.01.13}

Part A, 10 points for each problem.

\vspace{20pt}

\begin{enumerate}
\item It is known that $f'_x(x,y)>0$ and $f'_y(x,y)>0$. Sketch possible level curves for $f(x,y)$. What are the possible values of the angle between the gradient of the function $f$ and the $x$-axis?
\item Find the local maxima and minima of the function $f(x,y)=x^4+4y^4-xy$. Determine whether the extrema you have found are global or local.
\item Find and classify the constrained extrema of the function $f(x,y)=x+5y$ subject to $2x^2+y^2=10$.

\item Given the system
\[
\begin{cases}
xe^{u+v}+2uv=1 \\
ye^{u-v}-\frac{u}{1+v}=2x
\end{cases}
\]
find $du$ and $dv$ at $x_0 = 1$, $y_0 = 2$, $u_0 = 0$, $v_0 = 0$.

\item Find the total differential for the function $f(x,y)=x^2y^2+xy^2+2x+4y$. Using the total differential find approximately $f(1.001,1.999)$ 

\item Use the chain rule to find $f'(x)$ and $f''(x)$ for $f(x)=u(a,b,x)$ where $a=\cos(x)$ and $b=x^3$.

\end{enumerate}

\vspace{20pt}

Part B, 20 points for each problem.

\vspace{20pt}

\begin{enumerate}[resume]
\item A consumer maximizes the quasilinear utility function $u(x,y)=v(x)+y$, where $v'>0$, $v''<0$, subject to the budget constraint $px+y=I$.
\begin{enumerate}
\item (10 points) Denote the demand on $x$ by $x^*$. Show that $\frac{\partial x^*}{\partial I}=0$ and $\frac{\partial x^*}{\partial p}<0$.
\item (10 points) Let $V=u(x^*,y^*)$, where $(x^*,y^*)$ is the optimal bundle. Assuming that $y^*>0$ and using the appropriate envelope theorem, show that $\frac{\partial V}{\partial I}$ is constant. 
\end{enumerate}

\item A two-product firm produces outputs $y_1$ and $y_2$ from a single factor of production which is labor, in other words, there is a function $f$, such that $f(y_1,y_2)\leq \bar{L}$. Output prices are $p_1$ and $p_2$. The firm has a fixed amount of labor supply $\bar{L}>0$ that should be utilized in full.
\begin{enumerate}
\item (10 points) Set the problem of the revenue maximization under the labor constraint mathematically and derive first-order conditions. Assume that both outputs should be produced in positive amounts.
\item (10 points) Let the maximum value of the total revenue under the labor constraint be $TR(p_1,p_2,\bar{L})$. What are its derivatives with respect to the prices?
\end{enumerate}

\end{enumerate}

\subsection{MFE, mock, 28.03.2013}

Marks will be deducted for insufficient explanation within your answers. All problems are mandatory. Sections A and B will make up 60\% and 40\% of the exam grade, respectively. Total duration of the exam is 120 min. \\

\textbf{SECTION A}
\vspace{20pt}

\begin{enumerate}

\item Compute all the roots of the complex number, $\sqrt[5]{-1+i}$

\item The matrix $A$ has the eigenvalues $\lambda_1=-1$, $\lambda_2=3$, $\lambda_3=-2$.
\begin{enumerate}
\item Compute the eigenvalues of the following matrices: $B=A^2$, $C=A+3I$, $D=A^{-1}$ where $I$ is the corresponding identity matrix.
\item What can be said about the definiteness of these matrices?  
\end{enumerate} 
 
\item Consider the implicit function $y(x)$ given by the equation 
\[
y^3+y+3x^3+x^2=14.
\]
\begin{enumerate}
\item Does this equation define the implicit function $y(x)$ in the neighborhood of the point $(1,2)$? 
\item If the implicit function is defined find the Taylor series for $y(x)$ up to the second order term.
\end{enumerate}
 

\item Consider the difference equation $y_{t+1}(2+3y_t)=4y_t$ with initial condition $y_0=2/3$.
\begin{enumerate}
\item Using the substitution $z_t=1/y_t$ solve the difference equation.
\item What is the limit of $y_t$ as $t\to\infty$?
\end{enumerate}  

\item The homogeneous function $f$ is given by the equation 
\[ 
f(x,y)=\int_0^{xy^a} t^3+xt \, dt.
\]
Find the value of the parameter $a$ and the degree of homogeneity of $\partial f/\partial x$.

\item Find the two indefinite integrals $\int e^x \cos(2x)\,dx$, $\int \frac{x+1}{x^2-5x+4}\, dx$

\end{enumerate}

\vspace{20pt}
\textbf{SECTION B}
\vspace{20pt}

\begin{enumerate}[resume]
\item Suppose you enter a casino with $k$ dollars in your pocket. You decide to play a game in which you win \$1 with the probability  $2/3$ and lose \$1 dollar with the probability $1/3$. The game is over when $k=0$ (no money left) or $k=100$.

Denote the probability to win the game, i.e. reaching $k=100$, starting with $k$ dollars as $x_k=\P(win|k)$. Using the total probability formula 
\[
\P(win|k)=\frac{1}{3} \cdot \P(win|k-1)+\frac{2}{3} \cdot \P(win|k+1)
\] 
derive the difference equation for $x_k$ and solve the boundary-value problem with $x_0=0$ and $x_{100}=1$.

\item Let $N(t)$ denote the size of population, $X(t)=\sqrt{N}$ the total output in the economy. Consider the following model
\[
\frac{\dot{N}}{N}=\alpha-\beta\frac{N}{X}
\]
where $\alpha>0$, $\beta>0$. Find $N$ and explore its behavior as $t\to\infty$.
\end{enumerate}

% more variants :)
\begin{comment}

\newpage
\pagestyle{empty}
Mathematics for economists. Exam Paper. March 28, 2013, \textbf{Variant 2} \\ 

%Lecturer: K.A. Bukin
%Class teachers: A. Arlashin, G. Sharygin, S. Provornikov

Marks will be deducted for insufficient explanation within your answers. All problems are mandatory. Sections A and B will make up 60\% and 40\% of the exam grade, respectively. Total duration of the exam is 120 min. \\

\textbf{SECTION A}
\vspace{20pt}

\begin{enumerate}

\item Compute all the roots of the complex number, $\sqrt[5]{-1-i}$

\item The matrix $A$ has the eigenvalues $\lambda_1=-1$, $\lambda_2=4$, $\lambda_3=-2$.
\begin{enumerate}
\item Compute the eigenvalues of the following matrices: $B=A^2$, $C=A+3I$, $D=A^{-1}$ where $I$ is the corresponding identity matrix.
\item What can be said about the definiteness of these matrices?  
\end{enumerate} 
 
\item Consider the implicit function $y(x)$ given by the equation 
\[
y^3+2y+3x^3+x^2=16.
\]
\begin{enumerate}
\item Does this equation define the implicit function $y(x)$ in the neighborhood of the point $(1,2)$? 
\item If the implicit function is defined find the Taylor series for $y(x)$ up to the second order term.
\end{enumerate}
 

\item Consider the difference equation $y_{t+1}(2+3y_t)=4y_t$ with initial condition $y_0=2/3$.
\begin{enumerate}
\item Using the substitution $z_t=1/y_t$ solve the difference equation.
\item What is the limit of $y_t$ as $t\to\infty$?
\end{enumerate}  

\item The homogeneous function $f$ is given by the equation 
\[ 
f(x,y)=\int_0^{xy^a} t^3+xt \, dt.
\]
Find the value of the parameter $a$ and the degree of homogeneity of $\partial f/\partial x$.

\item Find the two indefinite integrals $\int e^x \cos(3x)\,dx$, $\int \frac{x+2}{x^2-5x+4}\, dx$

\end{enumerate}

\vspace{20pt}
\textbf{SECTION B}
\vspace{20pt}

\begin{enumerate}[resume]
\item Suppose you enter a casino with $k$ dollars in your pocket. You decide to play a game in which you win \$1 with the probability  $2/3$ and lose \$1 dollar with the probability $1/3$. The game is over when $k=0$ (no money left) or $k=100$.

Denote the probability to win the game, i.e. reaching $k=100$, starting with $k$ dollars as $x_k=\P(win|k)$. Using the total probability formula 
\[
\P(win|k)=\frac{1}{3} \cdot \P(win|k-1)+\frac{2}{3} \cdot \P(win|k+1)
\] 
derive the difference equation for $x_k$ and solve the boundary-value problem with $x_0=0$ and $x_{100}=1$.

\item Let $N(t)$ denote the size of population, $X(t)=\sqrt{N}$ the total output in the economy. Consider the following model
\[
\frac{\dot{N}}{N}=\alpha-\beta\frac{N}{X}
\]
where $\alpha>0$, $\beta>0$. Find $N$ and explore its behavior as $t\to\infty$.
\end{enumerate}


\newpage
\pagestyle{empty}
Mathematics for economists. Exam Paper. March 28, 2013, \textbf{Variant 3} \\ 

%Lecturer: K.A. Bukin
%Class teachers: A. Arlashin, G. Sharygin, S. Provornikov

Marks will be deducted for insufficient explanation within your answers. All problems are mandatory. Sections A and B will make up 60\% and 40\% of the exam grade, respectively. Total duration of the exam is 120 min. \\

\textbf{SECTION A}
\vspace{20pt}

\begin{enumerate}

\item Compute all the roots of the complex number, $\sqrt[5]{1-i}$

\item The matrix $A$ has the eigenvalues $\lambda_1=-1$, $\lambda_2=5$, $\lambda_3=-2$.
\begin{enumerate}
\item Compute the eigenvalues of the following matrices: $B=A^2$, $C=A+3I$, $D=A^{-1}$ where $I$ is the corresponding identity matrix.
\item What can be said about the definiteness of these matrices?  
\end{enumerate} 
 
\item Consider the implicit function $y(x)$ given by the equation 
\[
y^3+3y+3x^3+x^2=18.
\]
\begin{enumerate}
\item Does this equation define the implicit function $y(x)$ in the neighborhood of the point $(1,2)$? 
\item If the implicit function is defined find the Taylor series for $y(x)$ up to the second order term.
\end{enumerate}
 

\item Consider the difference equation $y_{t+1}(2+3y_t)=4y_t$ with initial condition $y_0=2/3$.
\begin{enumerate}
\item Using the substitution $z_t=1/y_t$ solve the difference equation.
\item What is the limit of $y_t$ as $t\to\infty$?
\end{enumerate}  

\item The homogeneous function $f$ is given by the equation 
\[ 
f(x,y)=\int_0^{xy^a} t^3+xt \, dt.
\]
Find the value of the parameter $a$ and the degree of homogeneity of $\partial f/\partial x$.

\item Find the two indefinite integrals $\int e^x \cos(4x)\,dx$, $\int \frac{x+3}{x^2-5x+4}\, dx$

\end{enumerate}

\vspace{20pt}
\textbf{SECTION B}
\vspace{20pt}

\begin{enumerate}[resume]
\item Suppose you enter a casino with $k$ dollars in your pocket. You decide to play a game in which you win \$1 with the probability  $2/3$ and lose \$1 dollar with the probability $1/3$. The game is over when $k=0$ (no money left) or $k=100$.

Denote the probability to win the game, i.e. reaching $k=100$, starting with $k$ dollars as $x_k=\P(win|k)$. Using the total probability formula 
\[
\P(win|k)=\frac{1}{3} \cdot \P(win|k-1)+\frac{2}{3} \cdot \P(win|k+1)
\] 
derive the difference equation for $x_k$ and solve the boundary-value problem with $x_0=0$ and $x_{100}=1$.

\item Let $N(t)$ denote the size of population, $X(t)=\sqrt{N}$ the total output in the economy. Consider the following model
\[
\frac{\dot{N}}{N}=\alpha-\beta\frac{N}{X}
\]
where $\alpha>0$, $\beta>0$. Find $N$ and explore its behavior as $t\to\infty$.
\end{enumerate}


\newpage
\pagestyle{empty}
Mathematics for economists. Exam Paper. March 28, 2013, \textbf{Variant 4} \\ 

%Lecturer: K.A. Bukin
%Class teachers: A. Arlashin, G. Sharygin, S. Provornikov

Marks will be deducted for insufficient explanation within your answers. All problems are mandatory. Sections A and B will make up 60\% and 40\% of the exam grade, respectively. Total duration of the exam is 120 min. \\

\textbf{SECTION A}
\vspace{20pt}

\begin{enumerate}

\item Compute all the roots of the complex number, $\sqrt[5]{1+i}$

\item The matrix $A$ has the eigenvalues $\lambda_1=-1$, $\lambda_2=6$, $\lambda_3=-2$.
\begin{enumerate}
\item Compute the eigenvalues of the following matrices: $B=A^2$, $C=A+3I$, $D=A^{-1}$ where $I$ is the corresponding identity matrix.
\item What can be said about the definiteness of these matrices?  
\end{enumerate} 
 
\item Consider the implicit function $y(x)$ given by the equation 
\[
y^3+4y+3x^3+x^2=20.
\]
\begin{enumerate}
\item Does this equation define the implicit function $y(x)$ in the neighborhood of the point $(1,2)$? 
\item If the implicit function is defined find the Taylor series for $y(x)$ up to the second order term.
\end{enumerate}
 

\item Consider the difference equation $y_{t+1}(2+3y_t)=4y_t$ with initial condition $y_0=2/3$.
\begin{enumerate}
\item Using the substitution $z_t=1/y_t$ solve the difference equation.
\item What is the limit of $y_t$ as $t\to\infty$?
\end{enumerate}  

\item The homogeneous function $f$ is given by the equation 
\[ 
f(x,y)=\int_0^{xy^a} t^3+xt \, dt.
\]
Find the value of the parameter $a$ and the degree of homogeneity of $\partial f/\partial x$.

\item Find the two indefinite integrals $\int e^x \cos(5x)\,dx$, $\int \frac{x+4}{x^2-5x+4}\, dx$

\end{enumerate}

\vspace{20pt}
\textbf{SECTION B}
\vspace{20pt}

\begin{enumerate}[resume]
\item Suppose you enter a casino with $k$ dollars in your pocket. You decide to play a game in which you win \$1 with the probability  $2/3$ and lose \$1 dollar with the probability $1/3$. The game is over when $k=0$ (no money left) or $k=100$.

Denote the probability to win the game, i.e. reaching $k=100$, starting with $k$ dollars as $x_k=\P(win|k)$. Using the total probability formula 
\[
\P(win|k)=\frac{1}{3} \cdot \P(win|k-1)+\frac{2}{3} \cdot \P(win|k+1)
\] 
derive the difference equation for $x_k$ and solve the boundary-value problem with $x_0=0$ and $x_{100}=1$.

\item Let $N(t)$ denote the size of population, $X(t)=\sqrt{N}$ the total output in the economy. Consider the following model
\[
\frac{\dot{N}}{N}=\alpha-\beta\frac{N}{X}
\]
where $\alpha>0$, $\beta>0$. Find $N$ and explore its behavior as $t\to\infty$.
\end{enumerate}
\end{comment}

\subsection{MOR, exam, 22.05.2013}


You need to solve exactly FIVE problems out of 7. At least ONE problem from each section should be chosen for solving. Each question is worth 20 points.

\vspace{20pt}
\textbf{SECTION A}
\vspace{20pt}

\begin{enumerate}
\item A two-product monopoly seeks to maximize its revenue which follows the formula $R(x,y)=6x-x^2+y-y^2$. The total costs function is given by $C(x,y)=x^2+y^2+4x+3y$, where $x$ and $y$ are the outputs.

State the problem of the monopoly, given condition that its profit $\pi=R-C$ should always remain nonnegative. Apply the Kuhn-Tucker conditions. Use Weierstrass theorem to confirm sufficiency.
\item For any real number $\lambda$, find the minimal value of the objective function $x_1+6x_2+2x_3+4x_4$ subject to the constraints  $\lambda x_1+x_2-x_3+x_4\geq -1$, $x_1+1.5x_2+x_3+x_4 \geq 5$,  all choice variables are nonnegative. 
\end{enumerate}

\vspace{20pt}
\textbf{SECTION B}
\vspace{20pt}

\begin{enumerate}[resume]
\item Solve the system of differential equations:
\[
\begin{cases}
\dot{x}=x-y \\
\dot{y}=2x-y
\end{cases}
\]
\item Given the Metzler equation of inventory cycles $y_t=3by_{t-1}-2by_{t-2}+N$, where $0<b<1$ and $N$ is a number, find all such values of $b$ for which solution represents convergent stepped time path (the complex roots case). Does the value of $N$ affect your conclusion?
\item Show that Chebyshev’s equation $(1-x^2)y''-xy'+y=0$, where $|x|<1$, can be reduced to equation $\ddot{y}+y=0$ by substituting $x=\cos t$. Hence find the general solution of Chebyshev’s equation.
\end{enumerate}

\vspace{20pt}
\textbf{SECTION C}
\vspace{20pt}

\begin{enumerate}[resume]
\item Find all pure and mixed Nash equilibria in the following bimatrix game:


\begin{tabular}{c|ccc}
 & d & e & f \\ 
\hline 
a & 4;5 & 1;4 & 1;1  \\ 
b & 2;8 & 5;0 & 0;4  \\ 
c & 0;3 & 2;2 & 5;7  \\ 
\end{tabular} 


\item There is an auction of a painting with two players. The value of the painting for the first player is a random variable $v_1$, for the second player --- $v_2$. The random variables $v_1$ and $v_2$ are independent and uniformly distributed from 0 to 1 million dollars. Each player makes the bid $b_i$ knowing only his own value of the painting. The player who makes the highest bid gets the painting and pays the arithmetic mean of the two bids. 

Find a Nash equilibrium where each player uses linear strategy of the form $b_i=k\cdot v_i$.

\end{enumerate}

\subsection{MOR, marking scheme, 22.05.2013 }

\begin{enumerate}
\item 5 points for setting Kuhn-Tucker Lagrangian correctly and writing down first-order conditions. Another 3 points for showing that the only constraint in the problem is binding. 5 points for proving that an internal  critical point ($x>0$, $y>0$) does not exist. Plus 3 points for finding corner critical point. And 4 points for showing that Weierstrass theorem is applicable.

\item 10 points for conversion to the dual program and correct analysis of the feasible region. The rest 10 points for maximizing objective function. 

\item 10 points for either finding eigen values +eigen vectors or rewarding the students who managed to reduce the system to one equation and solved it successfully. 10 points for finding general solution.

\item 5 points for finding roots of the characteristic equation. Another 10 points for finding interval for $b$ that provides convergent stepped time path. 5 points for conclusion that for these $b$ values the particular integral is represented by a constant and thus the value of   $N$ does not affect the answer.

\item 10 points for correct chain rule differentiation that reduces Chebyshev equation to the linear equation with the constant coefficients. Another 10 points for solving the latter and finding  after substitution $y=c_1 \sqrt{1-x^2}+c_2 x$.

\item Correct elimination of strictly dominated strategies --- 4 points. Correct picture of best response functions --- 12 points. The rest --- 4 points.  If only pure Nash Equilibria are found --- the total is 4 points.

\item 10 points for the payoff function of the first player given that his valuation of the painting is $v_1$ and his bid is $b_1$. If we denote by $W$ the win of the first player than the expected utility of the first player is given by:
\[
P(W) \left( v_1 - E[(b_1+b_2)/2 \mid W] \right) = \frac{b_1}{k} \left( v_1 - \frac{b_1+0.5b_1}{2}\right)
\]

5 points for stating FOC and 5 points for obtaining strategy from FOC. The final answer is $b_i=\frac{3}{8}v_i$.

\end{enumerate}



% more variants
\begin{comment}
\newpage
\pagestyle{empty}
Methods of Optimization. Exam Paper. May 22, 2013, \textbf{Variant 2} \\ 


Lecturer K. Bukin
Classteachers: B. Demeshev, D. Yesaulov, A. Kalchenko

You need to solve exactly FIVE problems out of 7. At least ONE problem from each section should be chosen for solving. Each question is worth 20 points.

\vspace{20pt}
\textbf{SECTION A}
\vspace{20pt}

\begin{enumerate}
\item A two-product monopoly seeks to maximize its revenue which follows the formula $R(x,y)=x-x^2+6y-y^2$. The total costs function is given by $C(x,y)=x^2+y^2+3x+4y$, where $x$ and $y$ are the outputs.

State the problem of the monopoly, given condition that its profit $\pi=R-C$ should always remain nonnegative. Apply the Kuhn-Tucker conditions. Use Weierstrass theorem to confirm sufficiency.
\item For any real number $\lambda$, find the minimal value of the objective function $4x_1+2x_2+10x_3+x_4$ subject to the constraints  $x_1+x_2+3x_3+x_4\leq 10$, $-x_1+x_2-2x_3+\lambda x_4 \leq 3$,  all choice variables are nonnegative. 
\end{enumerate}

\vspace{20pt}
\textbf{SECTION B}
\vspace{20pt}

\begin{enumerate}[resume]
\item Solve the system of differential equations:
\[
\begin{cases}
\dot{x}=-x+2y \\
\dot{y}=-x+y
\end{cases}
\]
\item Given the Metzler equation of inventory cycles $y_t=4by_{t-1}-3by_{t-2}+N$, where $0<b<1$ and $N$ is a number, find all such values of $b$ for which solution represents convergent stepped time path (the complex roots case). Does the value of $N$ affect your conclusion?
\item Show that Chebyshev’s equation $(1-x^2)y''-xy'+y=0$, where $|x|<1$, can be reduced to equation $\ddot{y}+y=0$ by substituting $x=\cos t$. Hence find the general solution of Chebyshev’s equation.
\end{enumerate}

\vspace{20pt}
\textbf{SECTION C}
\vspace{20pt}

\begin{enumerate}[resume]
\item Find all pure and mixed Nash equilibria in the following bimatrix game:


\begin{tabular}{c|ccc}
 & d & e & f \\ 
\hline 
a & 4;6 & 2;1 & 2;1  \\ 
b & 2;9 & 4;6 & 1;4  \\ 
c & 1;1 & 3;0 & 5;4  \\ 
\end{tabular} 


\item There is an auction of a painting with two players. The value of the painting for the first player is a random variable $v_1$, for the second player --- $v_2$. The random variables $v_1$ and $v_2$ are independent and uniformly distributed from 0 to 1 million dollars. Each player makes the bid $b_i$ knowing only his own value of the painting. The player who makes the highest bid gets the painting and pays the arithmetic mean of the two bids. 

Find a Nash equilibrium where each player uses linear strategy of the form $b_i=k\cdot v_i$.

\end{enumerate}

\newpage
\pagestyle{empty}
Methods of Optimization. Exam Paper. May 22, 2013, \textbf{Variant 3} \\ 


Lecturer K. Bukin
Classteachers: B. Demeshev, D. Yesaulov, A. Kalchenko

You need to solve exactly FIVE problems out of 7. At least ONE problem from each section should be chosen for solving. Each question is worth 20 points.

\vspace{20pt}
\textbf{SECTION A}
\vspace{20pt}

\begin{enumerate}
\item A two-product monopoly seeks to maximize its revenue which follows the formula $R(x,y)=2x-x^2+8y-y^2$. The total costs function is given by $C(x,y)=x^2+y^2+3.5x+6y$, where $x$ and $y$ are the outputs.

State the problem of the monopoly, given condition that its profit $\pi=R-C$ should always remain nonnegative. Apply the Kuhn-Tucker conditions. Use Weierstrass theorem to confirm sufficiency.
\item For any real number $\lambda$, find the minimal value of the objective function $4x_1+2x_2+10x_3+x_4$ subject to the constraints  $\lambda x_1+x_2+3x_3+x_4\leq  10$, $-x_1+x_2-2x_3-x_4 \leq 3$,  all choice variables are nonnegative. 
\end{enumerate}

\vspace{20pt}
\textbf{SECTION B}
\vspace{20pt}

\begin{enumerate}[resume]
\item Solve the system of differential equations:
\[
\begin{cases}
\dot{x}=x-y \\
\dot{y}=5x-y
\end{cases}
\]
\item Given the Metzler equation of inventory cycles $y_t=5by_{t-1}-4by_{t-2}+N$, where $0<b<1$ and $N$ is a number, find all such values of $b$ for which solution represents convergent stepped time path (the complex roots case). Does the value of $N$ affect your conclusion?
\item Show that Chebyshev’s equation $(1-x^2)y''-xy'+y=0$, where $|x|<1$, can be reduced to equation $\ddot{y}+y=0$ by substituting $x=\cos t$. Hence find the general solution of Chebyshev’s equation.
\end{enumerate}

\vspace{20pt}
\textbf{SECTION C}
\vspace{20pt}

\begin{enumerate}[resume]
\item Find all pure and mixed Nash equilibria in the following bimatrix game:


\begin{tabular}{c|ccc}
 & d & e & f \\ 
\hline 
a & 6;5 & 2;1 & 2;1  \\ 
b & 3;8 & 9;2 & 1;4  \\ 
c & 1;3 & 3;2 & 5;3  \\ 
\end{tabular} 


\item There is an auction of a painting with two players. The value of the painting for the first player is a random variable $v_1$, for the second player --- $v_2$. The random variables $v_1$ and $v_2$ are independent and uniformly distributed from 0 to 1 million dollars. Each player makes the bid $b_i$ knowing only his own value of the painting. The player who makes the highest bid gets the painting and pays the arithmetic mean of the two bids. 

Find a Nash equilibrium where each player uses linear strategy of the form $b_i=k\cdot v_i$.

\end{enumerate}

\newpage
\pagestyle{empty}
Methods of Optimization. Exam Paper. May 22, 2013, \textbf{Variant 4} \\ 


Lecturer K. Bukin
Classteachers: B. Demeshev, D. Yesaulov, A. Kalchenko

You need to solve exactly FIVE problems out of 7. At least ONE problem from each section should be chosen for solving. Each question is worth 20 points.

\vspace{20pt}
\textbf{SECTION A}
\vspace{20pt}

\begin{enumerate}
\item A two-product monopoly seeks to maximize its revenue which follows the formula $R(x,y)=8x-x^2+2y-y^2$. The total costs function is given by $C(x,y)=x^2+y^2+6x+3.5y$, where $x$ and $y$ are the outputs.

State the problem of the monopoly, given condition that its profit $\pi=R-C$ should always remain nonnegative. Apply the Kuhn-Tucker conditions. Use Weierstrass theorem to confirm sufficiency.
\item For any real number $\lambda$, find the minimal value of the objective function $x_1+5x_2+2x_3+4x_4$ subject to the constraints  $\lambda x_1+x_2-x_3+x_4\geq -1$, $x_1+1.5x_2+x_3+x_4 \geq 5$,  all choice variables are nonnegative. 
\end{enumerate}

\vspace{20pt}
\textbf{SECTION B}
\vspace{20pt}

\begin{enumerate}[resume]
\item Solve the system of differential equations:
\[
\begin{cases}
\dot{x}=-x+5y \\
\dot{y}=-x+y
\end{cases}
\]
\item Given the Metzler equation of inventory cycles $y_t=6by_{t-1}-5by_{t-2}+N$, where $0<b<1$ and $N$ is a number, find all such values of $b$ for which solution represents convergent stepped time path (the complex roots case). Does the value of $N$ affect your conclusion?
\item Show that Chebyshev’s equation $(1-x^2)y''-xy'+y=0$, where $|x|<1$, can be reduced to equation $\ddot{y}+y=0$ by substituting $x=\cos t$. Hence find the general solution of Chebyshev’s equation.
\end{enumerate}

\vspace{20pt}
\textbf{SECTION C}
\vspace{20pt}

\begin{enumerate}[resume]
\item Find all pure and mixed Nash equilibria in the following bimatrix game:


\begin{tabular}{c|ccc}
 & d & e & f \\ 
\hline 
a & 4;5 & 2;4 & 2;1  \\ 
b & 2;7 & 9;5 & 1;8  \\ 
c & 0;1 & 3;0 & 7;5  \\ 
\end{tabular} 


\item There is an auction of a painting with two players. The value of the painting for the first player is a random variable $v_1$, for the second player --- $v_2$. The random variables $v_1$ and $v_2$ are independent and uniformly distributed from 0 to 1 million dollars. Each player makes the bid $b_i$ knowing only his own value of the painting. The player who makes the highest bid gets the painting and pays the arithmetic mean of the two bids. 

Find a Nash equilibrium where each player uses linear strategy of the form $b_i=k\cdot v_i$.

\end{enumerate}

\end{comment}


\subsection{MOR, retake exam, 14.09.2013}


You need to solve exactly FIVE problems out of 7. At least ONE problem from each section should be chosen for solving. Each question is worth 20 points.

\vspace{20pt}
\textbf{SECTION A}
\vspace{20pt}

\begin{enumerate}
\item Maximise the function $f(x,y)=x+ay$, subject to $1-x^2\geq y^2$, $x+y \geq 0$ for all values of $a$ using the Lagrange multipliers approach. 

\item For any real number $\lambda$, find the minimal value of the objective function $x_1+6x_2+2x_3+4x_4$ subject to the constraints  $\lambda x_1+x_2-x_3+x_4\geq -1$, $2x_1+3x_2+2x_3+2x_4 \geq 10$,  all the choice variables are nonnegative. 
\end{enumerate}

\vspace{20pt}
\textbf{SECTION B}
\vspace{20pt}

\begin{enumerate}[resume]
\item Solve the system of differential equations:
\[
\begin{cases}
\dot{x}=2x+y+1 \\
\dot{y}=-2x+2y
\end{cases}
\]
\item Solve the difference equation $y_{t+2}-3y_{t+1}+2y_t=\sin(\pi t/2)$ and determine whether the solution paths are convergent or divergent.

\item In the model of interacting inflation and unemployment based on the Phillips relation,  both unemployment rate $U$ and expected inflation $\pi$ are the solutions of the system $\dot{\pi}=\frac{3}{4}(p-\pi)$, $\dot{U}=-\frac{1}{2}(m-p)$, where $m$ is exogenously defined positive rate of nominal money growth and $p$ is the posteriori observed inflation satisfying equation $p=\frac{1}{6}-3U+\pi$. Find the steady-state solutions for the inflation both expected and observed as well as the unemployment rate in terms of $m$. Explore the dynamic stability of solutions. What is the natural rate of unemployment?
\end{enumerate}

\vspace{20pt}
\textbf{SECTION C}
\vspace{20pt}

\begin{enumerate}[resume]
\item Find all pure and mixed Nash equilibria in the following bimatrix game:


\begin{tabular}{c|ccc}
 & d & e & f \\ 
\hline 
a & 5;5 & 2;6 & 0;4  \\ 
b & 2;1 & 0;2 & 4;3  \\ 
c & 0;4 & 3;5 & 1;0  \\ 
\end{tabular} 


\item Two players have found The Magic Box. The Box has two holes. Simulteneously each of the two players may put any amount of money from $0$ to $100$ euros into his hole. Then the Magic Box will multiply the total sum by $a>1$, divide the resulting sum into two equal parts and give them back to the players. The value of $a$ is known. Find all the pure and mixed Nash Equilibria of this game for all values of the parameter $a$.

\end{enumerate}

\section{2013-2014}

\subsection{MFE, mock, 31.10.13}

Marks will be deducted for insufficient explanation within your answers. All problems are mandatory. Sections A and B will make up 60\% and 40\% of the exam grade, respectively. Total duration of the exam is 120 min. \\

\textbf{SECTION A}

\begin{enumerate}

\item Find the angle between the gradients of the function $f(x,y,z)=x^3+xyz-2z^3$ at the points $(1,2,-1)$ and $(0,1,2)$.

\item Consider the function $f(x,y,z)=x^3+xyz-2z^3$. Using the total differential find the approximate value of $f(1.02,0.99,-0.98)$.

\item Consider the function $f(x,y,z)=x^4+(x+y)^2+(x+z)^3$. 
\begin{enumerate}
\item Find the Hesse matrix. Clearly state the Young theorem if you use it.
\item Find all the points where the Hesse matrix is positive definite.
\end{enumerate}

\item Consider the following system of equation:
\[
\begin{cases}
3xyzw+2x^3y^3z^3+4w^3=9\\
5x+y+z^3+w^3+w^2z^2=9
\end{cases}
\]
\begin{enumerate}
\item Does this system define functions $z(x,y)$ and $w(x,y)$ at a point $x=1$, $y=1$, $z=1$, $w=1$?
\item If it's possible find $\frac{\partial z}{\partial x}$ and $\frac{\partial w}{\partial y}$ at that point  
\end{enumerate}

\item Function $z(x,y)$ is given by the equation $z(x,y)=f(x^2+y^2)$. Simplify $y\frac{\partial z}{\partial x}-x\frac{\partial z}{\partial y}$.

\item A production function $y=f(x_1,x_2)$ exhibits constant returns to scale, that is $f(tx_1,tx_2)=tf(x_1,x_2)$ for every $t>0$, where $x_1, x_2 \geq 0$. Let $f_1(x_1,x_2)=\frac{\partial f}{\partial x_1}$ and $f_2(x_1,x_2)=\frac{\partial f}{\partial x_2}$. Find $\frac{\partial f_1(tx_1,tx_2)}{\partial t}$ and $\frac{\partial f_2(tx_1,tx_2)}{\partial t}$.

\end{enumerate}

\textbf{SECTION B}

\begin{enumerate}[resume]
\item A person has an option to buy a $x_0$ units of good at a price $p_0$ per unit. She can use her leisure time seeking a lower price $p(t)<p_0$, where $t$ is time spent on search. Her gain of finding a lower price provided the cost of search is $wt$, where $w$ is the wage rate, can be evaluated by the formula $g(t)=(p_0-p(t))x_0-wt$.
\begin{enumerate}
\item (10 points) Set the problem for maximizing the gain. Find the first-order condition. Assume that  $p'<0$ and $p''>0$.
\item (10 points) Let $t^*$ be optimal time of search. Using IFT find the formula for $\frac{\partial t^*}{\partial x_0}$ and determine its sign.  
\end{enumerate}
 
\item (20 points) Find $dz$ and $d^2z$ if the function $z$ is defined by the equation $F(x/z,y/z)=2013$. You may denote the derivatives of $F$ with respect to the first and the second arguments by $F_1$ and $F_2$ correspondingly.



\end{enumerate}



\subsection{MFE, mock, 31.10.13, Solution and marking scheme, A. Kalchenko, D. Esaulov}

\begin{enumerate}
\item Three partial derivatives --- $4$ points, Two gradient vectors --- $3$ points, cosine of the angle --- $2$ points, angle itself --- $1$ point.

\textit{Solution.}
\begin{equation*}\nabla f = (6 x^2+3 y z,3 x z,3 x y-3 z^2)\end{equation*}
\begin{equation*}g_1 = \nabla f(2,1,-1) = (21,-6,3)\end{equation*}
\begin{equation*}g_2 = \nabla f(0,1,-2) = (-6,0,-12)\end{equation*}
\begin{equation*}
\cos (\widehat{g_1,g_2}) = \frac {(g_1,g_2)}{\|g_1\|\|g_2\|} = \frac{-162}{\sqrt{486} \cdot \sqrt{180}}=-\sqrt{\frac{3}{10}}
\end{equation*}
\begin{equation*}
 (\widehat{g_1,g_2})  = \arccos(-\sqrt{\frac{3}{10}}) \approx 123 ^\circ
\end{equation*}

\item Three partial derivatives --- $4$ points (answers from the previous question may be used). Approximate $\Delta f$ --- $4$ points. Approximate $f$ --- $2$ points.

\textit{Solution.}
\begin{equation*}
f(1,1,-1) = 0
\end{equation*}
\begin{equation*}\nabla f = (6 x^2+3 y z,3 x z,3 x y-3 z^2)\end{equation*}
\begin{equation*}
\nabla f(1,1,-1) = (3,-3,0)
\end{equation*}
\begin{equation*}
\Delta f \approx (\nabla f)^T \cdot \left( \begin{array}{c}
\Delta x\\
\Delta y\\
\Delta z\\
\end{array}
\right)
 =\left(3,-3,0 \right)   \cdot \left( \begin{array}{c}
0.01\\
-0.01\\
0.02\\
\end{array}
\right) = 0.06
\end{equation*}
\begin{equation*}
f(1.01, 0.99, -0.98) \approx f(1,1,-1) +\Delta f =0.06
\end{equation*}


\item Hesse matrix --- $5$ points. Young theorem penalty --- $(-1)$ point. Small b --- $5$ points.

\textit{Solution.}
\begin{equation*}
\nabla f = \left(8 x^3+2 (x+y)+3 (x+z)^2,2 (x+y),3 (x+z)^2\right)
\end{equation*}
\begin{equation*}
D^2f =\left(
\begin{array}{ccc}
 2+24 x^2+6 (x+z) & 2 & 6 (x+z) \\
 2 & 2 & 0 \\
 6 (x+z) & 0 & 6 (x+z)
\end{array}
\right)
\end{equation*}

According to the Sylvester's criterion the matrix is positive definite iff $\Delta_1>0, \Delta_2>0, \Delta_3>0$:
\begin{equation*}
\begin{aligned}[c]
\left\{
\begin{array}{ccl}
\Delta_1 &=& 2+24 x^2+6 (x+z) >0\\
\Delta_2 &=& 48 x^2+12(x+z)>0\\
\Delta_3 &=&288 x^3+288 x^2 z>0\\
\end{array}
\right.
\end{aligned}
\quad\Longleftrightarrow\quad
\begin{aligned}[c]
\left\{
\begin{array}{l}
 12x^2+3 (x+z) +1>0\\
4x^2+(x+z)>0\\
x^2(x+z)>0\\
\end{array}
\right.
\end{aligned}
\end{equation*}

The Hesse matrix is positive definite at the points $(x,y,z)$ s.t. $x\neq0, x+z>0$


\item Sufficient conditions for the existence of the implicit function --- $2$ points. Two derivatives --- $8$ points.

\textit{Solution.}

Let $f_1 = 4x y z w+2x^3 y^3 z^3+4w^3-10, f_2=5 x+y+z^3+w^3+w^2 z^2-9$.

\begin{enumerate}
\item Check the conditions of the IFT:
	\begin{enumerate}
	\item $f_1(1,1,1,1) =0$, $f_2(1,1,1,1)=0$
	\item $f_1, f_2 \in C^1$
	\item \begin{equation*}
\left|\frac {\partial(f_1,f_2)}{\partial(z,w)}\right|=\left|
\begin{array}{cc}
 4 w x y+6 x^3 y^3 z^2 & 12 w^2+4 x y z \\
 2 w^2 z+3 z^2 & 3 w^2+2 w z^2
\end{array}
\right|=\left|
\begin{array}{cc}
 10 & 16 \\
 5 & 5
\end{array}
\right| = -30 \neq 0
\end{equation*}
	\end{enumerate}
\item 
\begin{equation*}
\frac{\partial z}{\partial x} = -\frac{\left|\frac {\partial(f_1,f_2)}{\partial(x,w)}\right|}{\left|\frac {\partial(f_1,f_2)}{\partial(z,w)}\right|} = -\frac{
\left|
\begin{array}{cc}
 4 w y z+6 x^2 y^3 z^3 & 12 w^2+4 x y z \\
 5 & 3 w^2+2 w z^2
\end{array}
\right|
} {
\left|
\begin{array}{cc}
 4 w x y+6 x^3 y^3 z^2 & 12 w^2+4 x y z \\
 2 w^2 z+3 z^2 & 3 w^2+2 w z^2
\end{array}
\right|} = -\frac{
\left|
\begin{array}{cc}
 10 & 16 \\
 5 & 5
\end{array}
\right|
}{
\left|
\begin{array}{cc}
 10 & 16 \\
 5 & 5
\end{array}
\right| 
} = -1
\end{equation*}
\begin{equation*}
\frac{\partial w}{\partial y} = -\frac{\left|\frac {\partial(f_1,f_2)}{\partial(z,y)}\right|}{\left|\frac {\partial(f_1,f_2)}{\partial(z,w)}\right|} = -\frac{
\left|
\begin{array}{cc}
 4 w x y+6 x^3 y^3 z^2 & 4 w x z+6 x^3 y^2 z^3 \\
 2 w^2 z+3 z^2 & 1
\end{array}
\right|
} {
\left|
\begin{array}{cc}
 4 w x y+6 x^3 y^3 z^2 & 12 w^2+4 x y z \\
 2 w^2 z+3 z^2 & 3 w^2+2 w z^2
\end{array}
\right|} = -\frac{
\left|
\begin{array}{cc}
 10 & 	10 \\
 5 & 1
\end{array}
\right|
}{
\left|
\begin{array}{cc}
 10 & 16 \\
 5 & 5
\end{array}
\right| 
} = -\frac 4 3
\end{equation*}
\end{enumerate}

\item Probably the easiest ;) Two derivatives --- $8$ points, simplify --- $2$ points.

\textit{Solution.}
\begin{equation*}
\begin{array}{l}
\frac{\partial z}{\partial x} = f'(x^2+y^2) \cdot 2x\\
\frac{\partial z}{\partial y} = f'(x^2+y^2) \cdot 2y\\
y\frac{\partial z}{\partial x}-x \frac{\partial z}{\partial y} = y \cdot 2xf'(x^2+y^2) - x \cdot 2y f'(x^2+y^2) =0
\end{array}
\end{equation*}


\item Showing that $f_i(tx_1,tx_2)=f_i(x_1,x_2)$ --- $6$ points, obtaining two zeros --- $4$ points. Typical given solutions: Using the fact that $f_i(tx_1,tx_2)=f_i(x_1,x_2)$ without proof --- penalty $(-4)$. Correct expression for $\frac{\partial f_i(tx_1,tx_2)}{\partial t}$ ignoring the fact that $f$ has constant returns to scale --- $4$ points in total.   

\textit{Solution.} Notice that $f_1 (tx_1,tx_2) = \frac{\partial f}{\partial x_1}(tx_1, tx_2).$ It means that you differentiate w.r.t. $x_1$ in the first place and only then you substitute the point $(tx_1, tx_2)$

\noindent Method 1. Differentiate the identity $f(tx_1,tx_2)=tf(x_1,x_2)$ w.r.t. $x_1$ by chain rule. You get
$$
f_1 (tx_1,tx_2)\cdot\underbrace{\frac{\partial (tx_1)}{\partial x_1}}_{=t} +  f_2 (tx_1,tx_2)\cdot\underbrace{\frac{\partial (tx_2)}{\partial x_1}}_{=0} = t f_1(x_1,x_2).
$$

Divide both sides by $t.$ You get 
$$
f_1(tx_1,tx_2) = f_1(x_1,x_2).
$$

By analogy $f_2(tx_1,tx_2) = f_2(x_1,x_2).$ Thus $f_i(tx_1,tx_2), \ i=1,2,$ are independent of $t$ and
$$
\frac{\partial f_1 (tx_1,tx_2)}{\partial t} = \frac{\partial f_2 (tx_1,tx_2)}{\partial t} = 0
$$

\noindent Method 2. By given conditions $f(x_1, x_2) = 1/t f(tx_1,tx_2).$ Therefore by chain rule
$$
f_1(x_1,x_2)=1/t \bigl(f_1 (tx_1,tx_2)\cdot\underbrace{\frac{\partial (tx_1)}{\partial x_1}}_{=t} +  f_2 (tx_1,tx_2)\cdot\underbrace{\frac{\partial (tx_2)}{\partial x_1}}_{=0}\bigr)=f_1(tx_1,tx_2).
$$
The conclusion is the same as in Method 1.


\item FOC --- $10$ points, derivative --- $5$ points, sign --- $5$ points.
\textit{Solution.}
\begin{equation*}
\begin{array}{ll}
\text{(a) }& g(t) \rightarrow \max_{t\geq0}\\
&\text{FOC:}\\
&g'(t) = -p'(t)x_0-w =0\\
\end{array}
\end{equation*}


(b) Optimal time $t^*$ satisfies the equation $F(t^*, x_0,w) = p'(t^*)x_0+w=0$. By IFT:
\begin{equation*}
\frac {\partial t^*}{\partial x_0} = - \frac {\frac {\partial F}{\partial x_0}} {\frac {\partial F}{\partial t^*}} = -\frac{p'(t^*)}{x_0p''(t^*)} > 0
\end{equation*}


\item $\frac{\partial z}{\partial x}$ --- $3$ points, $\frac{\partial z}{\partial y}$ --- $3$ points, expression for $dz$ --- $2$ points, second derivatives --- $3$ points each, expression for $d^2 z$ --- $3$ points.

\textit{Solution.} Denote $F_1 = \frac{\partial F}{\partial x}, F_2 = \frac{\partial F}{\partial y}.$ Notice that in fact $F_i=F_i(x/z,y/z), i=1,2.$
Firstly, we should mention that we can use IFT for $z=z(x,y)$ if the points (x,y,z) satisfy the condition $\frac{\partial F}{\partial z} = F_1 \cdot (-x/z^2)+ F_2 \cdot (-y/z^2)\neq 0.$

Next,
$$
dz = \frac{\partial z}{\partial x}dx+\frac{\partial z}{\partial y}dy.
$$

By IFT
\begin{gather*}
\frac{\partial z}{\partial x} = -\frac{\partial F}{\partial x}/\frac{\partial F}{\partial z} =-\frac{F_1\cdot (1/z)}{F_1\cdot(-x/z^2)+F_2\cdot(-y/z^2)}=\frac{F_1 z}{F_1 x+F_2 y}, \\ \frac{\partial z}{\partial y} =\dots= \frac{F_2 z}{F_1 x+F_2 y}.
\end{gather*}

Next,
$$
d^2z = \frac{\partial^2 z}{\partial x^2} (dx)^2 + (\frac{\partial^2 z}{\partial y \partial x}+\frac{\partial^2 z}{\partial x\partial y}) dx dy + \frac{\partial^2 z}{\partial y^2} (dy)^2.
$$
Let's find second derivatives:
\begin{align*}
\frac{\partial^2 z}{\partial x^2}= \frac{(F_1 x+F_2 y)(\frac{\partial F_1}{\partial x} z + F_1 \frac{\partial z}{\partial x} ) - F_1 z(F_1 + \frac{\partial F_1}{\partial x} x + \frac{\partial F_2}{\partial x} y)}{(F_1 x+F_2 y)^2},\\
%
\frac{\partial^2 z}{\partial y \partial x} = \frac{(F_1 x+F_2 y)(\frac{\partial F_1}{\partial y} z + F_1 \frac{\partial z}{\partial y} ) - F_1 z(F_2 + \frac{\partial F_1}{\partial y}x +\frac{\partial F_2}{\partial y} y)}{(F_1 x+F_2 y)^2},\\
%
\frac{\partial^2 z}{\partial x\partial y} = \frac{(F_1 x+F_2 y)(\frac{\partial F_2}{\partial x} z + F_2 \frac{\partial z}{\partial x} ) - F_2 z(F_1 + \frac{\partial F_1}{\partial x}x +\frac{\partial F_2}{\partial x} y)}{(F_1 x+F_2 y)^2},\\
%
\frac{\partial^2 z}{\partial y^2} = \frac{(F_1 x+F_2 y)(\frac{\partial F_2}{\partial y} z + F_2 \frac{\partial z}{\partial y} ) - F_2 z(F_2 + \frac{\partial F_2}{\partial y} y + \frac{\partial F_1}{\partial y} x)}{(F_1 x+F_2 y)^2}.
\end{align*} 


\end{enumerate}

\subsection{MFE, fall semester exam, 25.12.2013}

\textbf{SECTION A}

\begin{enumerate}
	\item Find the gradient of $f(x,y) =\frac{x^2y}{\sqrt{x^2+y^2}}$
at the point $M(2,1)$. Compute the derivative of $f$ at $M$ in direction of the vector $\{-1, 1\}$.
	\item The system of equations defines $x(z)$ and $y(z)$:
\begin{equation}
\begin{cases}
x^2+zxy+y^2+5z+y^3=9 \\
y^3x^2+3x+2y+z=7 \nonumber
\end{cases}
\end{equation}
Find $x'(z)$ and $y'(z)$ at the point $x=1$ and $y=1$. State the implicit function theorem.
 \item For the function $f(x,y)=x^3y^5+x^2-y^3+xy$ find first order Taylor approximation at the point $(1,1)$ and second order Taylor approximation at the same point.
	\item Find all stationary points of $f(x,y) = -2y^3+24y-x^2e^y$. Classify them as local minimum, maximum or saddle point.
	\item Find the constrained extrema of the function $f(x,y)=2x^2+x+y+y^2$ subject to $2x^2+y^2=5$.
	\item  For each value of $a$ determine whether the function $f(x,y,z)=x^2+xz+ayz+z^2$ is concave, convex, strictly concave, strictly convex.
\end{enumerate}

\textbf{SECTION B}

\begin{enumerate}[resume]
\item Robinson Crusoe produces nuts (good $x$) and corn (good $y$) using two factors of production: labor $L$ and land $T$ in accordance with the production functions, namely $x=\sqrt{L_x T_x}$ and $y=\sqrt{L_y T_y}$, where the $L_x$, $L_y$, $T_x$, $T_y$ are the quantities of labor and land employed by Crusoe in the production processes. The overall supply of labor and supply of the cultivated land equal 1. In order to find the \textbf{Production Possibilities Frontier} in the Crusoe’s economy the following problem should be solved:
\[
(A)\,
\begin{cases}
	\sqrt{L_x T_x} \to \max \\
	\sqrt{L_y T_y}=y=const \\
	L_x + L_y = 1, \, T_x + T_y = 1
\end{cases}
\]
In this problem all variables take nonnegative values and $0\leq y\leq 1$.

\begin{enumerate}
\item (15 points) Solve this maximization problem by the Lagrange multiplier method. You may consider only the case when $L_x,\, L_y,\, T_x, \, T_y>0$  and $0<y<1$.
\item (5 points) Let $L_x^*$, $L_y^*$, $T_x^*$, $T_y^*$ be the solution of problem (A) (optimal combination of factors). Then the produced quantities of nuts and corn equal $x=\sqrt{L_x^* T_x^*}$ and $y=\sqrt{L_y^* T_y^*}$. Find the relationship between $x$ and $y$ in the form of some equation $G(x,y)=0$.
\end{enumerate}

\item (continuation) Crusoe does not care about his leisure time and consumes nuts and corn. His utility function is $u(x,y)=\frac{1}{3}\ln x + \frac{2}{3}\ln y$. 

\begin{enumerate}
\item (10 points) By solving utility maximization problem: 
$
\begin{cases}
u(x,y) \to \max \\
G(x,y)=0
\end{cases},
$ find his optimal consumption bundle $(\tilde{x},\tilde{y})$.
\item (10 points) Crusoe has plowed more land in the amount of $dT$ (a small number). By using Envelope theorem find $\partial \tilde{x}/\partial T$. Hint. Firstly apply the theorem to problem (A).
\end{enumerate}

\end{enumerate}

\subsection{MFE, 25.12.2013, marking scheme}

\begin{enumerate}
\item $f'_x$ --- 3 points (2 for formula, 1 for value at  the point), $f'_y$ --- 3 points, the rest --- 4 points
\item Statement of IFT --- 2 points. Each derivative --- 4 points (3 for formula, 1 for calculations)
\item 4 points --- first order (1 pt for each first derivative, 2 pt for final formula), 6 points --- second order (1 pts for each second derivative, 3 pts for final formula)
\item Correct FOC --- 2 points, Solution of FOC --- 4 points. Check SOC --- 4 points.
\item NDCQ --- 1 pt, Correct FOC --- 2 pts, Solution of FOC --- 4 pts, check SOC --- 3 pts.
\item Hesse matrix --- 2 pts. Concavity and convexity --- 5 pts. Considering particular value of $a$ for strict concavity and strict convexity --- 3  pts.

\item Point a. NDCQ --- 2 pts. Writing FOC --- 3 pts. Solving FOC --- 5 pts. Checking SOC --- 5 pts. Point b --- 5 pts.

\item  Point a. NDCQ --- 1 pt. Writing FOC --- 2 pts. Solving FOC --- 4 pts. Checking SOC --- 3 pts. Point b. Solution 1. Applying Envelope theorem to problem (A) --- 5 pts, conclusion --- 5 pts. Solution 2. Applying IFT to the FOC --- 10 pts.

\end{enumerate}

\subsection{MFE, retake, 24.01.2014}

Part A.

\begin{enumerate}
\item Give an example of 
\begin{enumerate}
\item a function $f(x,y)$ that has a non-zero gradient in all the points except the point $(0,5)$ and zero gradient in the point $(0,5)$
\item a function $g(x,y)$ that has no gradient on the line $x=3y$ and a non-zero gradient when $x\neq 3y$
\end{enumerate}

\item The population of a certain country grows exponentially, $N_t= N_{1990}\cdot \exp (r(t-1990))$. The population was 70 million in 1990 and 80 million in 2000,
what will be the population in 2014?

\item Find and classify the extrema of the function $f(x,y)=x^2-y^2$ subject to $x^2+y^2=1$.

\item Given the system
\[
\begin{cases}
xe^{u+v}+2uv=1 \\
ye^{u-v}-\frac{u}{1+v}=2x
\end{cases}
\]
find $du$ and $dv$ at $x_0 = 1$, $y_0 = 2$, $u_0 = 0$, $v_0 = 0$.



\item Consider the objective function $f(x,y)=4kx^3+k^2xy+3ky^4-13x-13y$. The point $(x,y)=(1,1)$ is the maximum of the function. Find the value of $k$

\item In the macroeconomic linear IS-LM model for the closed economy
$Y=\bar{C}+m(Y-T)+G+\bar{I}-ar$ and $\bar{L}+bY-cr=M_s$, where $M_s$ is money supply, $r$ --- interest rate, $G$ --- government expenditures, $T$ --- lump sum tax and the constant parameters $\bar{C}>0$, $0<m<1$, $\bar{I}>0$, $a>0$, $\bar{L}>0$, $b>0$, $c>0$. Find the formulas for $dr/dT$, $dY/dT$. Assume that government expenditures and money supply are fixed exogenous variables.
\end{enumerate}


Part B.

\begin{enumerate}[resume]
\item The production function of a firm is given by $y=\sqrt{x_1}+\sqrt{x_2}$, where $x_1$ and $x_2$ are the factors of production. Given the factor prices $w_1=5w$, $w_2=w>0$ find the total costs function of the firm.
\item A consumer splits her time $\bar{L}$ hours a week between labor and leisure. Her utility function is represented by $u(c,l)=c^{\alpha}l^{1-\alpha}$, where $c$ is the amount of consumption and $l$ is leisure in hours and $0<\alpha<1$. The weekly budget constraint is written as $pc+wl=w\bar{L}$,
where $p$ is the price of consumption, $w$ is the hourly wage rate.
\begin{enumerate}
\item Find the consumer’s optimal bundle $(c^*,l^*)$. Justify your answer by checking second-order conditions or otherwise.
\item Let $\alpha=1/4$, $\bar{L}=168$, $p=10$, $w=5$. Using Envelope Theorem estimate the change in the maximum value of her utility if the wage rate has decreased by $0.5$.
\end{enumerate}

\end{enumerate}

\subsection{MFE, retake, marking scheme}

\begin{enumerate}
\item $5+5=10$, example $f(x,y)=x^2+(y-5)^2$, $f(x,y)=1/(x-3y)$
\item equation for $r$ 3 pts, the rest --- 7 pts. $e^r=(8/7)^{0.1}$
\item NDCQ --- 1 pt, formulated FOC --- 2 pts, solution --- 4 pts, SOC --- 3 pts, $(1,0)$, $(-1,0)$ --- maxima, $(0,1)$, $(0,-1)$ --- minima
\item Use of IFT --- 1 pt, four partial derivatives --- 6 pts, differentials --- 3 pts.
\item FOC, 2 values of $k$, $k_1=1$, $k_2=-13$ --- 6 pts, choice of $k=-13$ using SOC --- 4 pts.
\item 5 pts each derivative, $Y'(T)=cm/(cm-c-ab)$, $r'(T)=bm/(cm-c-ab)$
\item formulation of maximization problem --- 5 pts, NDCQ --- 2 pts, FOC --- 3 pts, solution of FOC --- 5 pts, SOC --- 5 pts
\item  NDCQ --- 2 pts, FOC --- 3 pts, solution of FOC --- 5 pts, SOC --- 5 pts, question b --- 5 pts. $pc=\alpha w\bar{L}$, $wl=(1-\alpha)w\bar{L}$
\end{enumerate}





\section{I wish more problems\ldots}

\begin{enumerate}
\item A production function $y=f(x_1,x_2)$ exhibits constant returns to scale, that is $f(tx_1,tx_2)=tf(x_1,x_2)$ for every $t>0$, where $x_1, x_2 \geq 0$. 
\begin{enumerate}
\item Let $f_1(x_1,x_2)=\frac{\partial f}{\partial x_1}$ and $f_2(x_1,x_2)=\frac{\partial f}{\partial x_2}$. Using the chain rule show that both partial derivatives of $f$ have the property $f_i(tx_1,tx_2)=f_i(x_1,x_2)$ for $i=1,2$.
\item Let $MRTS=f_1/f_2$. Show that its value remains the same along a straight line $x_2=\lambda x_1$, where $\lambda$ is a given positive number and $x_1, x_2>0$.
\end{enumerate}


\end{enumerate}

\end{document}
